import { describe, expect, it } from "vitest";
import { lintDriver } from "../../src/codegen/lint";
import type { GeneratedFile } from "../../src/codegen/types";
import type { DatasheetJson } from "../../src/schema/types";

// Session D §5: lintDriver must accept a COMPLETED cpp driver (class methods
// calling the right seam, same #define macros) unchanged, and keep enforcing
// thin-HAL purity / TODO / brace-balance rules on .hpp/.cpp content exactly as
// it already does on .h/.c (isHalImpl already exempts `_hal_<target>.c/.cpp` —
// see src/codegen/lint.ts). These files are built BY HAND here (mirroring the
// existing lint.test.ts pattern) since the cpp generator itself is the
// coder's job this session — this pins the shape lintDriver must accept.

const json: DatasheetJson = {
  metadata: {
    part: "CPPDEV",
    manufacturer: "Test Vendor",
    manufacturerConfidence: 1,
    pdfType: "text_based",
    pageCount: 1,
  },
  protocol: { bus: "I2C", addresses: ["0x50"] },
  interface: {
    kind: "register_map",
    registers: [
      { name: "ctrl", address: "0x00", reset: "0x00", width: 8, bitFields: [{ name: "en", msb: 0, lsb: 0 }] },
    ] as never,
  },
  validation: { valid: true, errors: [], warnings: [] },
};

function completedFiles(): GeneratedFile[] {
  const hpp = [
    "/*",
    " * CPPDEV driver — portable thin-HAL skeleton (generated by Driverge).",
    " */",
    "",
    "#ifndef CPPDEV_HPP",
    "#define CPPDEV_HPP",
    "",
    "#include <cstdint>",
    "",
    "#define CPPDEV_I2C_ADDR 0x50",
    "",
    "/* Register addresses. */",
    "#define CPPDEV_REG_CTRL 0x00",
    "",
    "/* Bit-field mask/shift accessors. */",
    "#define CPPDEV_CTRL_EN_MASK  0x01",
    "#define CPPDEV_CTRL_EN_SHIFT 0",
    "",
    'extern "C" {',
    "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
    "void hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
    "void hal_delay_ms (uint32_t ms);",
    "}",
    "",
    "class Cppdev {",
    "public:",
    "    int init();",
    "    int readRegister(uint8_t reg, uint8_t &value);",
    "    int writeRegister(uint8_t reg, uint8_t value);",
    "private:",
    "    uint8_t i2c_addr;",
    "};",
    "",
    "#endif /* CPPDEV_HPP */",
    "",
  ].join("\n");

  const cpp = [
    '#include "cppdev.hpp"',
    "",
    "int Cppdev::init() {",
    "    i2c_addr = CPPDEV_I2C_ADDR;",
    "    /* power-on sequence done. */",
    "    return 0;",
    "}",
    "",
    "int Cppdev::readRegister(uint8_t reg, uint8_t &value) {",
    "    hal_i2c_read(i2c_addr, reg, &value, 1);",
    "    return 0;",
    "}",
    "",
    "int Cppdev::writeRegister(uint8_t reg, uint8_t value) {",
    "    hal_i2c_write(i2c_addr, reg, &value, 1);",
    "    return 0;",
    "}",
    "",
  ].join("\n");

  return [
    { path: "cppdev.hpp", content: hpp },
    { path: "cppdev.cpp", content: cpp },
  ];
}

describe("lintDriver — completed cpp driver (class wrapper, same macros/seam)", () => {
  it("passes a completed, thin-HAL-pure cpp driver", () => {
    const r = lintDriver(completedFiles(), json);
    expect(r.errors).toEqual([]);
    expect(r.valid).toBe(true);
  });

  it("rejects a cpp core file calling STM32 CubeHAL directly (HAL_I2C_Mem_Read)", () => {
    const files = completedFiles().map((f) =>
      f.path === "cppdev.cpp"
        ? {
            path: f.path,
            content: f.content.replace(
              "return 0;\n}",
              "HAL_I2C_Mem_Read(0,0,0,0,0,0,0);\n    return 0;\n}",
            ),
          }
        : f,
    );
    const r = lintDriver(files, json);
    expect(r.valid).toBe(false);
    expect(r.errors.join("\n")).toMatch(/CubeHAL|hal_\* seam/);
  });

  it("rejects an unknown hal_* function in the cpp core", () => {
    const files = completedFiles().map((f) =>
      f.path === "cppdev.cpp"
        ? {
            path: f.path,
            content: f.content.replace(
              "return 0;\n}",
              "hal_gpio_set(1);\n    return 0;\n}",
            ),
          }
        : f,
    );
    const r = lintDriver(files, json);
    expect(r.valid).toBe(false);
    expect(r.errors.join("\n")).toMatch(/hal_gpio_set/);
  });

  it("still rejects leftover TODO(driverge) markers on .hpp/.cpp content", () => {
    const files = completedFiles().map((f) =>
      f.path === "cppdev.hpp"
        ? { path: f.path, content: `${f.content}\n/* TODO(driverge): finish this */\n` }
        : f,
    );
    const r = lintDriver(files, json);
    expect(r.valid).toBe(false);
    expect(r.errors.join("\n")).toMatch(/TODO\(driverge\)/);
  });

  it("still rejects unbalanced braces on .cpp content", () => {
    const files = completedFiles().map((f) =>
      f.path === "cppdev.cpp" ? { path: f.path, content: `${f.content}\nint stray(void) {` } : f,
    );
    const r = lintDriver(files, json);
    expect(r.valid).toBe(false);
    expect(r.errors.join("\n")).toMatch(/braces/);
  });

  it("still catches a corrupted bit-field mask on .hpp content", () => {
    const files = completedFiles().map((f) =>
      f.path === "cppdev.hpp"
        ? { path: f.path, content: f.content.replace("CPPDEV_CTRL_EN_MASK  0x01", "CPPDEV_CTRL_EN_MASK  0x00") }
        : f,
    );
    const r = lintDriver(files, json);
    expect(r.valid).toBe(false);
    expect(r.errors.join("\n")).toMatch(/EN_MASK/);
  });
});

// Contract amendment (orchestrator, post-GREEN 4b3da14/d576ba6): a native
// target's cpp seam file is `_hal_<target>.cpp` (not .c) — see
// tests/codegen/cpp-native.test.ts. lintDriver's isHalImpl already exempts
// `_hal_[a-z0-9]+\.(?:c|cpp)$` (verified during Session D RED, unchanged by
// this amendment), so a completed cpp NATIVE bundle (core + a `.cpp` seam
// calling a vendor API directly) must still pass — this is a confirmation
// pin, not a new RED, since isHalImpl's regex already covered .cpp.
describe("lintDriver — completed cpp NATIVE bundle (seam file is _hal_<target>.cpp)", () => {
  it("accepts a cpp core + a `_hal_esp32.cpp` seam that calls ESP-IDF directly (isHalImpl matches .cpp)", () => {
    const seam: GeneratedFile = {
      path: "cppdev_hal_esp32.cpp",
      content: [
        '#include "cppdev.hpp"',
        '#include "driver/i2c_master.h"',
        "",
        "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
        "    (void)addr; (void)reg;",
        "    i2c_master_transmit(0, 0, 0, 0);",
        "    (void)data; (void)len;",
        "}",
        "",
        "void hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
        "    (void)addr; (void)reg;",
        "    i2c_master_transmit_receive(0, 0, 0, 0, 0, 0);",
        "    (void)data; (void)len;",
        "}",
        "",
        "void hal_delay_ms (uint32_t ms) {",
        "    (void)ms;",
        "}",
        "",
      ].join("\n"),
    };
    const r = lintDriver([...completedFiles(), seam], json);
    expect(r.errors).toEqual([]);
    expect(r.valid).toBe(true);
  });

  it("still rejects the same ESP-IDF call if it leaks into the cpp CORE instead of the seam", () => {
    const leaked = completedFiles().map((f) =>
      f.path === "cppdev.cpp"
        ? { path: f.path, content: f.content.replace("return 0;\n}", "i2c_master_transmit(0,0,0,0);\n    return 0;\n}") }
        : f,
    );
    const r = lintDriver(leaked, json);
    expect(r.valid).toBe(false);
    expect(r.errors.join("\n")).toMatch(/ESP-IDF/);
  });
});
