// ESP32 (ESP-IDF) target. Per platform-code-generation-targets, a native target
// does NOT replace the thin HAL — it *pre-fills* the seam. So the ESP32 driver is
// the exact portable core (unchanged, still platform-agnostic) PLUS a
// <part>_hal_esp32.c that implements hal_i2c_*/hal_delay_ms with the ESP-IDF v5
// i2c_master driver. The user drops all three files into an ESP-IDF component;
// only the board's bus/pin bring-up stays a TODO(driverge).
//
// I2C-only: the seam hard-codes the ESP-IDF i2c_master driver and references
// `${PREFIX}_I2C_ADDR`, so this target refuses (UnsupportedBusError) any part
// whose protocol.bus isn't "I2C" rather than emit an uncompilable seam.

import type { DatasheetJson } from "../schema/types.js";
import { prefixOf, slug } from "./ident.js";
import { generatePortableDriver } from "./portable.js";
import { UnsupportedBusError } from "./types.js";
import type { DriverArtifact, GeneratedFile } from "./types.js";

function halImpl(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — ESP-IDF (i2c_master) HAL seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with the",
    " * ESP-IDF v5 i2c_master driver. In your app: create an I2C master bus with",
    ` * i2c_new_master_bus() for your SDA/SCL pins, then call ${name}_esp32_bind()`,
    " * once before using the driver. The driver core stays byte-for-byte portable.",
    " */",
    `#include "${name}.h"`,
    "#include <string.h>",
    '#include "driver/i2c_master.h"',
    '#include "freertos/FreeRTOS.h"',
    '#include "freertos/task.h"',
    "",
    `#ifndef ${prefix}_I2C_TIMEOUT_MS`,
    `#define ${prefix}_I2C_TIMEOUT_MS 1000`,
    "#endif",
    "",
    `static i2c_master_dev_handle_t s_${name}_dev;`,
    "",
    `/* Add the device (at ${prefix}_I2C_ADDR) to an existing I2C master bus and keep`,
    " * the handle for the hal_* calls. Call once after i2c_new_master_bus(). */",
    `esp_err_t ${name}_esp32_bind(i2c_master_bus_handle_t bus, uint32_t scl_speed_hz) {`,
    "    i2c_device_config_t cfg = {",
    "        .dev_addr_length = I2C_ADDR_BIT_LEN_7,",
    `        .device_address = ${prefix}_I2C_ADDR,`,
    "        .scl_speed_hz = scl_speed_hz,",
    "    };",
    `    return i2c_master_bus_add_device(bus, &cfg, &s_${name}_dev);`,
    "}",
    "",
    "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    "    uint8_t buf[33];",
    "    (void)addr; /* the device handle already encodes the bus address */",
    "    if ((size_t)len + 1u > sizeof buf) {",
    "        return;",
    "    }",
    "    buf[0] = reg;",
    "    memcpy(&buf[1], data, len);",
    `    i2c_master_transmit(s_${name}_dev, buf, (size_t)len + 1u, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_i2c_read(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    "    (void)addr;",
    `    i2c_master_transmit_receive(s_${name}_dev, &reg, 1, data, len, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    vTaskDelay(pdMS_TO_TICKS(ms));",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_esp32.c`, content };
}

/** Portable core + an ESP-IDF seam implementation for the same part. */
export function generateEsp32Driver(json: DatasheetJson): DriverArtifact {
  if (json.protocol.bus !== "I2C") {
    throw new UnsupportedBusError("esp32", json.protocol.bus);
  }
  const name = slug(json.metadata.part);
  const prefix = prefixOf(json.metadata.part);
  const base = generatePortableDriver(json);

  return {
    files: [...base.files, halImpl(name, prefix)],
    fill_in_brief: {
      ...base.fill_in_brief,
      hal_setup_todo: `Bring up the ESP-IDF I2C master bus (i2c_new_master_bus with your SDA/SCL GPIOs and port), then call ${name}_esp32_bind(bus, 400000) before the first driver call. Tune ${prefix}_I2C_TIMEOUT_MS if needed.`,
    },
  };
}
