// ESP32 (ESP-IDF) target. Per platform-code-generation-targets, a native target
// does NOT replace the thin HAL — it *pre-fills* the seam. So the ESP32 driver is
// the exact portable core (unchanged, still platform-agnostic) PLUS a
// <part>_hal_esp32.c that implements the bus's thin-HAL seam + hal_delay_ms with
// ESP-IDF v5 drivers. The user drops all three files into an ESP-IDF component;
// only the board's bus/pin bring-up stays a TODO(driverge).
//
// I2C/SPI only: the I2C seam references `${PREFIX}_I2C_ADDR`, a macro the
// portable core only defines for I2C parts, and the SPI seam needs the portable
// core's hal_spi_transfer declaration — any other bus (UART, unknown) has no
// ESP-IDF seam here, so this target refuses (UnsupportedBusError) rather than
// emit an uncompilable seam.

import type { DatasheetJson } from "../schema/types.js";
import { prefixOf, slug } from "./ident.js";
import { generatePortableDriver } from "./portable.js";
import { UnsupportedBusError } from "./types.js";
import type { DriverArtifact, GeneratedFile } from "./types.js";

function halImplI2c(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — ESP-IDF (i2c_master) HAL seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with the",
    " * ESP-IDF v5 i2c_master driver. In your app: create an I2C master bus with",
    ` * i2c_new_master_bus() for your SDA/SCL pins, then call ${name}_esp32_bind()`,
    " * once before using the driver. The driver core stays byte-for-byte portable.",
    " */",
    `#include "${name}.h"`,
    "#include <string.h>",
    '#include "driver/i2c_master.h"',
    '#include "freertos/FreeRTOS.h"',
    '#include "freertos/task.h"',
    "",
    `#ifndef ${prefix}_I2C_TIMEOUT_MS`,
    `#define ${prefix}_I2C_TIMEOUT_MS 1000`,
    "#endif",
    "",
    `static i2c_master_dev_handle_t s_${name}_dev;`,
    "",
    `/* Add the device (at ${prefix}_I2C_ADDR) to an existing I2C master bus and keep`,
    " * the handle for the hal_* calls. Call once after i2c_new_master_bus(). */",
    `esp_err_t ${name}_esp32_bind(i2c_master_bus_handle_t bus, uint32_t scl_speed_hz) {`,
    "    i2c_device_config_t cfg = {",
    "        .dev_addr_length = I2C_ADDR_BIT_LEN_7,",
    `        .device_address = ${prefix}_I2C_ADDR,`,
    "        .scl_speed_hz = scl_speed_hz,",
    "    };",
    `    return i2c_master_bus_add_device(bus, &cfg, &s_${name}_dev);`,
    "}",
    "",
    "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    "    uint8_t buf[33];",
    "    (void)addr; /* the device handle already encodes the bus address */",
    "    if ((size_t)len + 1u > sizeof buf) {",
    "        return;",
    "    }",
    "    buf[0] = reg;",
    "    memcpy(&buf[1], data, len);",
    `    i2c_master_transmit(s_${name}_dev, buf, (size_t)len + 1u, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_i2c_read(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    "    (void)addr;",
    `    i2c_master_transmit_receive(s_${name}_dev, &reg, 1, data, len, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    vTaskDelay(pdMS_TO_TICKS(ms));",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_esp32.c`, content };
}

function halImplSpi(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — ESP-IDF (spi_master) HAL seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with the",
    " * ESP-IDF v5 spi_master driver: one half-duplex, polling transaction per",
    ` * hal_spi_transfer() call. In your app: bring up the SPI bus with`,
    " * spi_bus_initialize() for your MOSI/MISO/SCLK pins, then call",
    ` * ${name}_esp32_bind() once before using the driver. The driver core stays`,
    " * byte-for-byte portable.",
    " */",
    `#include "${name}.h"`,
    "#include <string.h>",
    '#include "driver/spi_master.h"',
    '#include "freertos/FreeRTOS.h"',
    '#include "freertos/task.h"',
    "",
    `static spi_device_handle_t s_${name}_dev;`,
    "",
    "/* Add the device to an already-initialized SPI bus (spi_bus_initialize'd",
    " * `host`) and keep the handle for the hal_* calls. Call once at startup;",
    " * see fill_in_brief.hal_setup_todo for the SPI mode this part expects. */",
    `esp_err_t ${name}_esp32_bind(spi_host_device_t host, int cs_gpio, int clock_hz) {`,
    "    spi_device_interface_config_t cfg = {",
    "        .flags = SPI_DEVICE_HALFDUPLEX,",
    "        .spics_io_num = cs_gpio,",
    "        .clock_speed_hz = clock_hz,",
    "        .mode = 0, /* see fill_in_brief.hal_setup_todo for this part's SPI mode */",
    "        .queue_size = 1,",
    "    };",
    `    return spi_bus_add_device(host, &cfg, &s_${name}_dev);`,
    "}",
    "",
    "void hal_spi_transfer(const uint8_t *tx, uint16_t tx_len, uint8_t *rx, uint16_t rx_len) {",
    "    spi_transaction_t t;",
    "    memset(&t, 0, sizeof t);",
    "    t.length = 8 * tx_len;",
    "    t.rxlength = 8 * rx_len;",
    "    t.tx_buffer = tx;",
    "    t.rx_buffer = rx;",
    `    spi_device_polling_transmit(s_${name}_dev, &t);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    vTaskDelay(pdMS_TO_TICKS(ms));",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_esp32.c`, content };
}

/** Portable core + an ESP-IDF seam implementation for the same part. */
export function generateEsp32Driver(json: DatasheetJson): DriverArtifact {
  const bus = json.protocol.bus;
  if (bus !== "I2C" && bus !== "SPI") {
    throw new UnsupportedBusError("esp32", bus);
  }
  const name = slug(json.metadata.part);
  const prefix = prefixOf(json.metadata.part);
  const base = generatePortableDriver(json);

  const hal = bus === "SPI" ? halImplSpi(name, prefix) : halImplI2c(name, prefix);
  const hal_setup_todo =
    bus === "SPI"
      ? `Bring up the ESP-IDF SPI bus (spi_bus_initialize with your MOSI/MISO/SCLK pins and host), then call ${name}_esp32_bind(host, cs_gpio, clock_hz) before the first driver call. Confirm this part's SPI mode (0-3) and maximum clock speed from the datasheet's SPI timing section.`
      : `Bring up the ESP-IDF I2C master bus (i2c_new_master_bus with your SDA/SCL GPIOs and port), then call ${name}_esp32_bind(bus, 400000) before the first driver call. Tune ${prefix}_I2C_TIMEOUT_MS if needed.`;

  return {
    files: [...base.files, hal],
    fill_in_brief: {
      ...base.fill_in_brief,
      hal_setup_todo,
    },
  };
}
