// Portable thin-HAL codegen. Renders a deterministic C driver skeleton from the
// frozen DatasheetJson: register/command constants, bit-field mask+shift macros,
// the per-bus thin-HAL seam (I2C: <slug>_hal_i2c_read/write + <slug>_hal_delay_ms;
// SPI: one combined <slug>_hal_spi_transfer + <slug>_hal_delay_ms — see busSeam
// below and thin-hal-non-negotiable) and NOTHING platform-specific, function
// stubs, and TODO(driverge) markers at every spot needing host-AI reasoning.
// Every thin-HAL seam symbol is PER-DRIVER PREFIXED (`<slug>_hal_*`, slug =
// slug(json.metadata.part)) — see decisions: per-driver-seam-prefixing. A bare
// `hal_*` name collides at link the moment a project has two Driverge drivers
// (see raw/stm32-test-results/*.md); the prefix makes every driver's seam
// symbol set disjoint from every other driver's. Output is reproducible: no
// timestamps, stable ordering. The host AI fills the brief and re-validates via
// validate_driver.

import { registerWidth, type Register } from "../pdf/types.js";
import type { Command, DatasheetJson } from "../schema/types.js";
import { HEX_ONLY, commentSafe, fieldMask, hexOrUndefined, macro, maskHex, slug } from "./ident.js";
import type { DriverArtifact, FillInBrief, GeneratedFile } from "./types.js";

// Exported: the "cpp" language flavor (see portable-cpp.ts) renders the SAME
// #define macro / TODO blocks and thin-HAL seam declarations as this C
// generator — reusing these pure helpers instead of re-deriving them is how the
// two flavors stay byte-for-byte consistent on everything except the
// struct-vs-class/free-function-vs-method shape (see Session D: cpp language
// option).
// part/mfr/busLine are free text lifted verbatim from the parsed datasheet
// (metadata.part/manufacturer; busLine's only free-text ingredient is the I2C
// address, which is hex-validated, but commentSafe-ing the whole trio here —
// once, in the one place every AUTOGEN caller shares — is simpler and safer
// than re-deriving which piece is "safe enough" at each call site) — see B2:
// comment-escape injection. commentSafe neutralizes any embedded `*/`/`/*` so
// none of the three can ever prematurely close (or spoof) this block comment.
// `name` is the seam slug (never free text — see ident.ts's slug()) so it is
// embedded directly with no commentSafe-ing needed.
export const AUTOGEN = (name: string, part: string, mfr: string, busLine: string): string =>
  [
    "/*",
    ` * ${commentSafe(part)} driver — portable thin-HAL skeleton (generated by Driverge).`,
    ` * Manufacturer: ${commentSafe(mfr)}`,
    ` * ${commentSafe(busLine)}`,
    " *",
    " * This is a deterministic skeleton. Every TODO(driverge) marks a spot the",
    " * host AI must complete (init sequence, vendor quirks, docs) using the",
    " * datasheet JSON, then confirm with the validate_driver tool.",
    " *",
    ` * Portability rule: this driver calls ONLY its own ${name}_hal_* seam below —`,
    " * never a vendor peripheral API directly. Implement the seam once per",
    " * platform. The seam is per-driver prefixed so multiple Driverge drivers",
    " * in one project never collide at link (see thin-hal-non-negotiable).",
    " */",
  ].join("\n");

// ---------------------------------------------------------------------------
// register_map
// ---------------------------------------------------------------------------

export function registerConstants(prefix: string, registers: Register[]): string[] {
  const lines: string[] = ["/* Register addresses. */"];
  const seen = new Set<string>();
  for (const r of registers) {
    if (!HEX_ONLY.test(r.address)) continue; // skip ranges like "0xE1…0xF0"
    const macroName = `${prefix}_REG_${macro(r.name)}`;
    if (seen.has(macroName)) continue;
    seen.add(macroName);
    lines.push(`#define ${macroName} ${r.address.toUpperCase().replace("0X", "0x")}`);
  }
  return lines;
}

/** Where the host AI must enumerate a register map that Driverge couldn't extract. */
export function registerMapTodo(prefix: string, pages: number[]): string[] {
  const where = pages.length
    ? ` (register section detected on page(s) ${pages.join(", ")})`
    : "";
  return [
    "/* Register map. */",
    "/* TODO(driverge): Driverge could not auto-extract this device's register map",
    ` * from the datasheet${where}. Enumerate the registers from the datasheet (read`,
    " * the driverge://datasheet resource) and add one line per register:",
    ` *     #define ${prefix}_REG_<NAME> 0x..`,
    ` * plus ${prefix}_<REG>_<FIELD>_MASK / _SHIFT macros for any bit fields. */`,
  ];
}

/** Where the host AI must enumerate a command set that Driverge couldn't extract. */
export function commandSetTodo(prefix: string, pages: number[]): string[] {
  const where = pages.length
    ? ` (command section detected on page(s) ${pages.join(", ")})`
    : "";
  return [
    "/* Command codes. */",
    "/* TODO(driverge): Driverge could not auto-extract this device's command set",
    ` * from the datasheet${where}. Enumerate the commands from the datasheet (read`,
    " * the driverge://datasheet resource) and add one line per command:",
    ` *     #define ${prefix}_CMD_<NAME> 0x.. */`,
  ];
}

/** fill_in_brief.register_map_todo text — shared by the C and cpp generators. */
export function registerMapTodoText(json: DatasheetJson, name: string, prefix: string): string {
  return `Enumerate ${json.metadata.part || name}'s register map from the datasheet — Driverge could not auto-extract it. Add a "#define ${prefix}_REG_<NAME> 0x.." for each register address (and ${prefix}_<REG>_<FIELD>_MASK/_SHIFT for bit fields) using the driverge://datasheet resource, then wire the read/write helpers accordingly.`;
}

/** fill_in_brief.command_set_todo text — shared by the C and cpp generators. */
export function commandSetTodoText(json: DatasheetJson, name: string, prefix: string): string {
  return `Enumerate ${json.metadata.part || name}'s command set from the datasheet — Driverge could not auto-extract it. Add a "#define ${prefix}_CMD_<NAME> 0x.." for each command using the driverge://datasheet resource.`;
}

// ---------------------------------------------------------------------------
// bus -> thin-HAL seam registry
// ---------------------------------------------------------------------------
//
// Each supported register_map bus contributes: the seam declaration line(s)
// (rendered in the header, right below the "Thin-HAL seam" comment), the
// driver-handle struct field, and the read_register/write_register bodies.
// <slug>_hal_delay_ms is common to every bus and stays outside this table.
// Session C adds a CAN row here — keep each row self-contained so a new bus
// never touches the others.
//
// busSeam(name) builds this table FRESH per driver (rather than a static
// Record) because every declared function name, and every readBody/writeBody
// call, must embed `name` (the seam slug) — see the module header comment
// (per-driver seam prefixing). `name` is never free text (ident.ts's slug()
// only emits [a-z0-9_]), so it is safe to splice directly into both generated
// C identifiers and RegExp sources (lint.ts) with no further escaping.
//
// UART and CAN are the odd rows out: neither has a universal register-access
// primitive — UART is just a byte pipe, and CAN register/config access is
// device-specific (CANopen SDO, J1939 PGNs, raw message-ID schemes) — so
// read_register/write_register have no honest implementation here. Their
// readBody/writeBody are therefore unused (see framingBody below, which
// renders a TODO(driverge) framing gap directly in
// registerDriver/commandDriver instead of a seam call) — kept as empty arrays
// purely so BusSeam's shape stays uniform across buses.

export type RegisterMapBus = "I2C" | "SPI" | "UART" | "CAN";

interface BusSeam {
  /** Lines appended after the "Thin-HAL seam" header comment, in order. */
  decl: string[];
  /** Field(s) for the driver handle typedef struct. */
  handleField: string;
  /** Body of <name>_read_register (dev, reg, value already in scope). Unused for UART/CAN. */
  readBody: string[];
  /** Body of <name>_write_register (dev, reg, value already in scope). Unused for UART/CAN. */
  writeBody: string[];
}

/**
 * Per-driver-prefixed thin-HAL seam table. See the section header comment
 * above for why this is a builder (keyed on `name`) rather than a static
 * Record — every declared symbol and every call site below embeds `name`.
 */
export function busSeam(name: string): Record<RegisterMapBus, BusSeam> {
  return {
    I2C: {
      decl: [
        "/* Return 0 on success, non-zero on a bus error (e.g. NACK). */",
        `int ${name}_hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);`,
        `int ${name}_hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);`,
      ],
      handleField: "    uint8_t i2c_addr;",
      readBody: [`    return ${name}_hal_i2c_read(dev->i2c_addr, reg, value, 1);`],
      writeBody: [`    return ${name}_hal_i2c_write(dev->i2c_addr, reg, &value, 1);`],
    },
    // Session E: full-duplex contract (see the field-test plan's finding B).
    // One call = one CS-framed, full-duplex transaction; rx may be NULL for a
    // write-only transfer. Most register reads are the half-duplex
    // write-then-read idiom over that full-duplex primitive: pad tx with a
    // dummy 0x00 byte after the address so the response lands at the matching
    // rx offset (rx[0] is garbage clocked in while tx[0]=reg goes out, rx[1]
    // is the value) — see readBody below. TUSS4470-style same-frame-response
    // (genuinely full-duplex) devices have the host AI fill tx/rx directly in
    // a custom TODO(driverge) spot without touching this seam signature.
    SPI: {
      decl: [
        "/* One call = one CS-framed, full-duplex transaction: CS is asserted, len",
        " * bytes are clocked out from tx while len bytes are simultaneously clocked",
        " * in to rx, then CS is deasserted. rx may be NULL for a write-only",
        " * transfer (tx is still fully clocked out). Returns 0 on success,",
        " * non-zero on a bus error.",
        " *",
        " * Half-duplex write-then-read idiom (most register reads): pad tx with a",
        " * dummy 0x00 byte after the register address so the device's response",
        " * lands at the matching rx offset — e.g. tx = {reg, 0x00}; rx[0] is",
        " * garbage (clocked in while tx[0]=reg goes out) and rx[1] is the",
        " * register's value. */",
        `int ${name}_hal_spi_transfer(const uint8_t *tx, uint8_t *rx, uint16_t len);`,
      ],
      handleField: `    uint8_t _reserved; /* platform CS handled in ${name}_hal_spi_transfer */`,
      readBody: [
        "    uint8_t tx[2];",
        "    uint8_t rx[2];",
        "    int status;",
        "    tx[0] = reg;",
        "    tx[1] = 0x00;",
        `    status = ${name}_hal_spi_transfer(tx, rx, 2);`,
        "    *value = rx[1];",
        "    return status;",
      ],
      writeBody: [
        "    uint8_t tx[2];",
        "    tx[0] = reg;",
        "    tx[1] = value;",
        `    return ${name}_hal_spi_transfer(tx, NULL, 2);`,
      ],
    },
    UART: {
      decl: [
        `/* ${name}_hal_uart_write is a blocking write of len bytes. */`,
        `/* ${name}_hal_uart_read reads up to len bytes and returns the count`,
        " * actually read within timeout_ms. */",
        `void ${name}_hal_uart_write(const uint8_t *data, uint16_t len);`,
        `uint16_t ${name}_hal_uart_read(uint8_t *data, uint16_t len, uint32_t timeout_ms);`,
      ],
      handleField: `    uint8_t _reserved; /* platform UART handle is bound inside the ${name}_hal_uart_* implementation */`,
      readBody: [],
      writeBody: [],
    },
    // Session C — CAN. Unlike I2C's two-function read/write pair or SPI's single
    // transfer, one <name>_hal_can_transfer() call both sends a frame AND
    // (optionally) waits for the one response frame it provokes — CAN has no
    // separate read/write primitive, only "put a frame on the bus, addressed
    // by arbitration id, and maybe get one back". rx_len is in/out (capacity
    // in, actual byte count out) because a CAN payload is 0-8 bytes, not a
    // fixed size.
    CAN: {
      decl: [
        "/* A call sends one CAN frame to arbitration id `id` and optionally waits",
        " * for one response frame (pass rx/rx_len NULL/0 to only transmit).",
        " * Returns 0 on success. rx_len is in/out: in = buffer capacity, out =",
        " * bytes actually received. */",
        `int ${name}_hal_can_transfer(uint32_t id, const uint8_t *tx, uint8_t tx_len, uint8_t *rx, uint8_t *rx_len, uint32_t timeout_ms);`,
      ],
      handleField: `    uint8_t _reserved; /* platform CAN peripheral/arbitration-id binding is handled inside the ${name}_hal_can_transfer implementation */`,
      readBody: [],
      writeBody: [],
    },
  };
}

/** Which busSeam row a protocol.bus resolves to. "unknown" defaults to the I2C
 *  seam, matching the pre-existing (pre-Session-B) fallback behavior. */
export function seamBusFor(bus: string): RegisterMapBus {
  if (bus === "SPI") return "SPI";
  if (bus === "UART") return "UART";
  if (bus === "CAN") return "CAN";
  return "I2C";
}

// UART and CAN have no universal register/command framing (start bytes, IDs,
// checksums, arbitration ids are all device-specific — see decisions:
// thin-hal-non-negotiable), so rather than fabricate a wire format, the
// generated body is a deliberate TODO(driverge) reasoning gap over the raw
// seam call(s): a compilable placeholder (params voided, returns -1) that
// names the PREFIXED seam function(s) so the host AI knows exactly what to
// build on top of. See fill_in_brief.framing_todo.
export function uartFramingBody(name: string, params: string[]): string[] {
  return [
    "    /* TODO(driverge): this device has no universal UART register/command",
    `     * framing — build the request frame and call ${name}_hal_uart_write(),`,
    `     * then parse the response via ${name}_hal_uart_read(). See`,
    "     * fill_in_brief.framing_todo. */",
    ...params.map((p) => `    (void)${p};`),
    "    return -1;",
  ];
}

export function canFramingBody(name: string, params: string[]): string[] {
  return [
    "    /* TODO(driverge): this device has no universal CAN register/command",
    `     * framing — build the CAN frame and call ${name}_hal_can_transfer() with`,
    "     * this part's arbitration id to send it (and receive any response). See",
    "     * fill_in_brief.framing_todo. */",
    ...params.map((p) => `    (void)${p};`),
    "    return -1;",
  ];
}

// CAN-specific reasoning gap shared by both interface kinds: which arbitration
// id / SDO index / message ID maps to which register or command is
// device-specific and belongs in fill_in_brief.quirks_todo, NOT a generic
// checksum note reused from UART.
export const CAN_QUIRKS_NOTE =
  "Confirm the arbitration IDs / SDO message schema this part uses for register/command access from the datasheet; CAN device interfaces are device-specific.";

export function bitFieldMacros(prefix: string, registers: Register[]): string[] {
  const lines: string[] = [];
  for (const r of registers) {
    if (r.bitFields.length === 0) continue;
    const width = registerWidth(r);
    const widthNote = width > 8 ? ` (${width}-bit register)` : "";
    // r.name is free text lifted verbatim from the parsed datasheet — see B2:
    // comment-escape injection — so it must not be allowed to close this
    // block comment early via an embedded `*/`.
    lines.push("", `/* ${commentSafe(r.name)} bit fields${widthNote}. */`);
    for (const f of r.bitFields) {
      const base = `${prefix}_${macro(r.name)}_${macro(f.name)}`;
      lines.push(`#define ${base}_MASK  ${maskHex(fieldMask(f.msb, f.lsb, width), width)}`);
      lines.push(`#define ${base}_SHIFT ${f.lsb}`);
    }
  }
  return lines;
}

function registerDriver(
  json: DatasheetJson,
  registers: Register[],
  name: string,
  prefix: string,
): DriverArtifact {
  const busKind = seamBusFor(json.protocol.bus);
  const spi = busKind === "SPI";
  const uart = busKind === "UART";
  const can = busKind === "CAN";
  const seam = busSeam(name)[busKind];
  const addr = hexOrUndefined(json.protocol.addresses?.[0]);
  const guard = `${prefix}_H`;
  const type = `${name}_t`;

  const header: string[] = [
    AUTOGEN(
      name,
      json.metadata.part || name,
      json.metadata.manufacturer,
      spi
        ? "Bus: SPI"
        : uart
          ? "Bus: UART"
          : can
            ? "Bus: CAN"
            : `Bus: I2C, address ${addr ?? "(unknown — see TODO)"}`,
    ),
    "",
    `#ifndef ${guard}`,
    `#define ${guard}`,
    "",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    '#ifdef __cplusplus',
    'extern "C" {',
    "#endif",
    "",
  ];

  if (!spi && !uart && !can) {
    if (addr) {
      header.push("/* I2C device address. */", `#define ${prefix}_I2C_ADDR ${addr}`, "");
    } else {
      header.push(
        "/* TODO(driverge): set the I2C device address (not found in the datasheet parse). */",
        `#define ${prefix}_I2C_ADDR 0x00`,
        "",
      );
    }
  }

  const regLines = registerConstants(prefix, registers);
  const hasRegs = regLines.some((l) => l.startsWith("#define"));
  header.push(
    ...(hasRegs
      ? regLines
      : registerMapTodo(prefix, json.extraction?.detectedPages ?? [])),
  );
  if (registers.some((r) => registerWidth(r) > 8)) {
    header.push(
      "",
      "/* NOTE: some registers here are wider than 8 bits (see the per-register",
      " * annotations). Bit-field masks are register-width correct; multi-byte access",
      " * framing (byte order / transfer size) is device-specific and belongs on the",
      " * hal_* seam. */",
    );
  }
  const bits = bitFieldMacros(prefix, registers);
  if (bits.length > 0) header.push("", "/* Bit-field mask/shift accessors. */", ...bits);

  header.push(
    "",
    "/* Thin-HAL seam — implement these for your platform (see thin-hal). */",
    ...seam.decl,
    `void ${name}_hal_delay_ms (uint32_t ms);`,
    "",
    "/* Driver handle. */",
    `typedef struct {`,
    seam.handleField,
    `} ${type};`,
    "",
    "/* Public API. */",
    `int ${name}_init(${type} *dev);`,
    `int ${name}_read_register(${type} *dev, uint8_t reg, uint8_t *value);`,
    `int ${name}_write_register(${type} *dev, uint8_t reg, uint8_t value);`,
    "",
    '#ifdef __cplusplus',
    "}",
    "#endif",
    `#endif /* ${guard} */`,
    "",
  );

  // The I2C/SPI seam bodies now END with `return <slug>_hal_..._transfer/read/write(...)`,
  // propagating the seam's status (0 = success) to the caller — a NACK/bus error
  // is no longer swallowed (A7). So no trailing `return 0` is appended here.
  const readBody = uart
    ? uartFramingBody(name, ["dev", "reg", "value"])
    : can
      ? canFramingBody(name, ["dev", "reg", "value"])
      : ["    if (dev == NULL || value == NULL) {", "        return -1;", "    }", ...seam.readBody];
  const writeBody = uart
    ? uartFramingBody(name, ["dev", "reg", "value"])
    : can
      ? canFramingBody(name, ["dev", "reg", "value"])
      : ["    if (dev == NULL) {", "        return -1;", "    }", ...seam.writeBody];

  const source: string[] = [
    `#include "${name}.h"`,
    "",
    `int ${name}_init(${type} *dev) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    ...(spi || uart || can ? [] : [`    dev->i2c_addr = ${prefix}_I2C_ADDR;`]),
    ...registerInitTodo(name, uart, can, `${name}_write_register`),
    "    return 0;",
    "}",
    "",
    `int ${name}_read_register(${type} *dev, uint8_t reg, uint8_t *value) {`,
    ...readBody,
    "}",
    "",
    `int ${name}_write_register(${type} *dev, uint8_t reg, uint8_t value) {`,
    ...writeBody,
    "}",
    "",
  ];

  const brief = registerBrief(json);
  if (!hasRegs) {
    brief.register_map_todo = registerMapTodoText(json, name, prefix);
  }
  return {
    files: makeFiles(name, header, source),
    fill_in_brief: brief,
  };
}

/**
 * Names the register_map fill_in_brief prose uses to refer to the driver's own
 * init/read/write entry points. Defaults to the C free-function names
 * (`<name>_init`, `read_register`/`write_register`); the cpp generator passes
 * the class method names instead so the SAME brief builder produces
 * language-accurate text without duplicating the quirks/framing prose (Session
 * D: cpp language option).
 */
export interface RegisterBriefCalls {
  init: string;
  readRegister: string;
  writeRegister: string;
}

export function registerBrief(
  json: DatasheetJson,
  calls?: Partial<RegisterBriefCalls>,
): FillInBrief {
  const part = json.metadata.part || "the device";
  const name = slug(part);
  const c: RegisterBriefCalls = {
    init: calls?.init ?? `${name}_init`,
    readRegister: calls?.readRegister ?? "read_register",
    writeRegister: calls?.writeRegister ?? "write_register",
  };
  const quirks = [
    `Capture vendor timing/behavior quirks for ${part} (e.g. mandatory power-on delay, soft-reset requirement, read-back constraints) and enforce them in ${c.init} using ${name}_hal_delay_ms.`,
  ];
  if (json.protocol.bus === "SPI") {
    quirks.push(
      `Verify the register address bit convention: many SPI chips set the address MSB for reads (e.g. 0x80 | reg) — check the datasheet's SPI framing and adjust ${c.readRegister}/${c.writeRegister}.`,
    );
  }
  if (json.protocol.bus === "UART") {
    quirks.push(
      "Verify the response checksum algorithm from the datasheet before trusting frame data — vendor checksum/CRC methods for UART command-and-response parts vary.",
    );
  }
  if (json.protocol.bus === "CAN") {
    quirks.push(CAN_QUIRKS_NOTE);
  }
  const brief: FillInBrief = {
    init_sequence_todo: `Determine the correct power-on/reset init sequence for ${part}: which registers to write, in what order, with what values (mode/config), and any required startup delay. Read the datasheet init/operation section via the driverge://datasheet resource.`,
    quirks_todo: quirks.join(" "),
    doc_todo:
      "Add Doxygen comments for all public functions and any device-specific compensation/conversion formulas.",
  };
  if (json.protocol.bus === "UART") {
    brief.framing_todo = `Implement ${name}'s UART frame protocol in ${c.readRegister}/${c.writeRegister}: build request frames with ${name}_hal_uart_write and parse responses with ${name}_hal_uart_read, per the datasheet's communication/frame-format section.`;
  }
  if (json.protocol.bus === "CAN") {
    brief.framing_todo = `Implement ${name}'s CAN frame protocol in ${c.readRegister}/${c.writeRegister}: build request frames and call ${name}_hal_can_transfer() with this part's arbitration id(s), per the datasheet's CAN communication/message-ID section.`;
  }
  return brief;
}

// ---------------------------------------------------------------------------
// command_set
// ---------------------------------------------------------------------------

function commandDriver(
  json: DatasheetJson,
  commands: Command[],
  name: string,
  prefix: string,
): DriverArtifact {
  const uart = json.protocol.bus === "UART";
  const can = json.protocol.bus === "CAN";
  const noAddrBus = uart || can; // neither UART nor CAN has a bus device address
  const addr = hexOrUndefined(json.protocol.addresses?.[0]);
  const crc = commands.find((c) => c.crc)?.crc;
  const guard = `${prefix}_H`;
  const type = `${name}_t`;
  const seamTable = busSeam(name);

  const header: string[] = [
    AUTOGEN(
      name,
      json.metadata.part || name,
      json.metadata.manufacturer,
      uart
        ? "Bus: UART · command-set device"
        : can
          ? "Bus: CAN · command-set device"
          : `Bus: I2C, address ${addr ?? "(unknown — see TODO)"} · command-set device`,
    ),
    "",
    `#ifndef ${guard}`,
    `#define ${guard}`,
    "",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    '#ifdef __cplusplus',
    'extern "C" {',
    "#endif",
    "",
  ];

  if (noAddrBus) {
    // No bus device address on UART/CAN — only I2C command-set parts get an
    // *_I2C_ADDR macro (see fill_in_brief.framing_todo for the UART/CAN
    // reasoning gap this leaves instead).
  } else if (addr) {
    header.push("/* I2C device address. */", `#define ${prefix}_I2C_ADDR ${addr}`, "");
  } else {
    header.push(
      "/* TODO(driverge): set the I2C device address. */",
      `#define ${prefix}_I2C_ADDR 0x00`,
      "",
    );
  }

  if (commands.length === 0) {
    header.push(...commandSetTodo(prefix, json.extraction?.detectedPages ?? []));
  } else {
    header.push("/* Command codes. */");
    const seen = new Set<string>();
    for (const c of commands) {
      const macroName = `${prefix}_CMD_${macro(c.name)}`;
      if (seen.has(macroName)) continue;
      seen.add(macroName);
      const line = `#define ${macroName} ${c.code.toUpperCase().replace("0X", "0x")}`;
      // c.params is currently always hex-derived (prose-commands.ts) and thus
      // safe as-is, but the Command type doesn't guarantee that — commentSafe
      // defensively, same reasoning as AUTOGEN/bitFieldMacros above (B2).
      header.push(
        c.params && c.params.length > 0
          ? `${line}  /* params: ${commentSafe(c.params.join(", "))} */`
          : line,
      );
    }
  }

  // A non-hex crc.poly/init (e.g. containing an embedded newline) must never
  // reach a #define as a live value (define-injection fix) — only emit the
  // block when BOTH are well-formed hex literals; skip it entirely otherwise
  // (crc8Body/commandBrief still reference the macro NAMES, not the raw
  // values, so no injected content survives as code either way).
  if (crc && hexOrUndefined(crc.poly) && hexOrUndefined(crc.init)) {
    header.push(
      "",
      `/* CRC-${crc.width} checksum parameters. */`,
      `#define ${prefix}_CRC_POLY ${crc.poly}`,
      `#define ${prefix}_CRC_INIT ${crc.init}`,
    );
  }

  header.push(
    "",
    "/* Thin-HAL seam — implement these for your platform (see thin-hal). */",
    ...(uart ? seamTable.UART.decl : can ? seamTable.CAN.decl : seamTable.I2C.decl),
    `void ${name}_hal_delay_ms (uint32_t ms);`,
    "",
    "/* Driver handle. */",
    "typedef struct {",
    uart ? seamTable.UART.handleField : can ? seamTable.CAN.handleField : seamTable.I2C.handleField,
    `} ${type};`,
    "",
    "/* Public API. */",
    `int ${name}_init(${type} *dev);`,
    `int ${name}_send_command(${type} *dev, uint16_t command);`,
    `int ${name}_read_data(${type} *dev, uint8_t *buffer, uint16_t len);`,
    ...(crc ? [`uint8_t ${name}_crc8(const uint8_t *data, uint16_t len);`] : []),
    "",
    '#ifdef __cplusplus',
    "}",
    "#endif",
    `#endif /* ${guard} */`,
    "",
  );

  const source: string[] = [
    `#include "${name}.h"`,
    "",
    `int ${name}_init(${type} *dev) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    ...(noAddrBus ? [] : [`    dev->i2c_addr = ${prefix}_I2C_ADDR;`]),
    ...COMMAND_INIT_TODO,
    "    return 0;",
    "}",
    "",
    `int ${name}_send_command(${type} *dev, uint16_t command) {`,
    ...(uart
      ? uartFramingBody(name, ["dev", "command"])
      : can
        ? canFramingBody(name, ["dev", "command"])
        : [
            "    uint8_t msb;",
            "    uint8_t lsb;",
            "    if (dev == NULL) {",
            "        return -1;",
            "    }",
            "    msb = (uint8_t)(command >> 8);",
            "    lsb = (uint8_t)(command & 0xFF);",
            ...I2C_COMMAND_FRAME_NOTE,
            `    return ${name}_hal_i2c_write(dev->i2c_addr, msb, &lsb, 1);`,
          ]),
    "}",
    "",
    `int ${name}_read_data(${type} *dev, uint8_t *buffer, uint16_t len) {`,
    ...(uart
      ? uartFramingBody(name, ["dev", "buffer", "len"])
      : can
        ? canFramingBody(name, ["dev", "buffer", "len"])
        : [
            "    if (dev == NULL || buffer == NULL) {",
            "        return -1;",
            "    }",
            ...commandReadDataTodo(`${name}_crc8`),
            "    (void)dev;",
            "    (void)buffer;",
            "    (void)len;",
            "    return 0;",
          ]),
    "}",
    "",
  ];

  if (crc) {
    source.push(...crc8Body(`${name}_crc8`, crc, prefix));
  }

  const brief = commandBrief(json, commands, crc, uart, can, name, prefix);
  return { files: makeFiles(name, header, source), fill_in_brief: brief };
}

/**
 * Names the command_set fill_in_brief prose uses for the driver's own entry
 * points. Defaults to the C free-function names; the cpp generator passes the
 * class method names instead (Session D: cpp language option) — see
 * RegisterBriefCalls for the register_map analogue.
 */
export interface CommandBriefCalls {
  sendCommand: string;
  readData: string;
  crc8: string;
}

export function commandBrief(
  json: DatasheetJson,
  commands: Command[],
  crc: Command["crc"] | undefined,
  uart: boolean,
  can: boolean,
  name: string,
  prefix: string,
  calls?: Partial<CommandBriefCalls>,
): FillInBrief {
  const c: CommandBriefCalls = {
    sendCommand: calls?.sendCommand ?? `${name}_send_command`,
    readData: calls?.readData ?? `${name}_read_data`,
    crc8: calls?.crc8 ?? `${name}_crc8`,
  };
  const brief: FillInBrief = {
    init_sequence_todo: `Determine the power-up / soft-reset sequence and any startup delay for ${json.metadata.part || "the device"}.`,
    quirks_todo: uart
      ? `Verify the response checksum algorithm from the datasheet before trusting ${c.readData}'s output — vendor checksum/CRC methods vary by part.`
      : can
        ? CAN_QUIRKS_NOTE
        : `Implement ${c.readData} for this part's actual read framing (clock stretching vs. fixed delay, number of data+CRC words per command) using the driverge://datasheet resource.`,
    doc_todo: "Add Doxygen comments for all public functions and document each command's response layout.",
  };
  if (crc) {
    brief.crc_todo = `Implement ${c.crc8}: CRC-${crc.width}, polynomial ${crc.poly}, init ${crc.init}, per the datasheet checksum section.`;
  }
  if (commands.length === 0) {
    brief.command_set_todo = commandSetTodoText(json, name, prefix);
  }
  if (uart) {
    brief.framing_todo = `Implement ${name}'s UART frame protocol in ${c.sendCommand}/${c.readData}: build request frames with ${name}_hal_uart_write and parse responses with ${name}_hal_uart_read, per the datasheet's communication/frame-format section.`;
  }
  if (can) {
    brief.framing_todo = `Implement ${name}'s CAN frame protocol in ${c.sendCommand}/${c.readData}: build request frames and call ${name}_hal_can_transfer() with this part's arbitration id(s), per the datasheet's CAN communication/message-ID section.`;
  }

  return brief;
}

// ---------------------------------------------------------------------------

/**
 * Static prose block shared by the C and cpp command_set init() bodies
 * (mentions no function names, so there is nothing to parameterize).
 */
export const COMMAND_INIT_TODO: readonly string[] = [
  "    /* TODO(driverge): power-up / soft-reset sequence and startup delay. See",
  "     * fill_in_brief.init_sequence_todo. */",
];

/** The I2C command-frame comment in send_command — no callable names, shared verbatim. */
export const I2C_COMMAND_FRAME_NOTE: readonly string[] = [
  "    /* Command frame = [MSB][LSB]. The I2C write seam emits the reg byte then",
  "     * the data bytes, so MSB-as-reg + LSB-as-data yields the correct 2-byte frame. */",
];

/**
 * read_data's "implement the actual read framing" TODO comment. `crc8Name` is
 * the bare callable name (no parens) — `<name>_crc8` for C, `crc8` for cpp.
 */
export function commandReadDataTodo(crc8Name: string): string[] {
  return [
    "    /* TODO(driverge): read `len` response bytes (data words each followed by a",
    "     * CRC byte). Most command-set parts use a plain I2C read with no pointer",
    "     * byte — adapt the HAL call to your platform, then check each word with",
    `     * ${crc8Name}(). See fill_in_brief.quirks_todo. */`,
  ];
}

/**
 * Renders a CRC-8 stub function/method body. `qualifiedName` is the full
 * callable name to emit — a free function (`sht3x_crc8`) for C or a qualified
 * method (`Sht3x::crc8`) for cpp — so this single builder covers both without
 * duplicating the TODO prose (Session D: cpp language option).
 */
export function crc8Body(
  qualifiedName: string,
  crc: NonNullable<Command["crc"]>,
  prefix: string,
): string[] {
  return [
    `uint8_t ${qualifiedName}(const uint8_t *data, uint16_t len) {`,
    "    (void)data;",
    "    (void)len;",
    `    /* TODO(driverge): implement CRC-${crc.width} (poly ${prefix}_CRC_POLY, init`,
    `     * ${prefix}_CRC_INIT) per the datasheet checksum section. See`,
    "     * fill_in_brief.crc_todo. */",
    "    return 0;",
    "}",
    "",
  ];
}

/**
 * register_map init()'s "implement the power-on/reset sequence" TODO comment.
 * `name` is the seam slug, used to name the PREFIXED seam function(s) in the
 * uart/can branch. The uart/can branch mentions no OTHER callable names, so it
 * is identical for C and cpp; the register-access branch takes the write call
 * as a parameter (`<name>_write_register` for C, `writeRegister` for cpp — no
 * trailing `()`: portable.test.ts's assertFullDuplexWrite locates the real
 * write_register FUNCTION by regex-searching for the first
 * `<name>_write_register(` in the source, so this TODO prose must not spell
 * the call with a paren immediately after the name or it would shadow that
 * search) so both flavors share this one builder (Session D: cpp language
 * option).
 */
export function registerInitTodo(
  name: string,
  uart: boolean,
  can: boolean,
  writeRegisterCall: string,
): string[] {
  if (uart || can) {
    return [
      "    /* TODO(driverge): implement the power-on / reset init sequence — the",
      "     * correct command/frame sequence and any required startup delay. See",
      "     * fill_in_brief.init_sequence_todo and fill_in_brief.framing_todo. Use",
      `     * ${uart ? `${name}_hal_uart_write()/${name}_hal_uart_read()` : `${name}_hal_can_transfer()`} and`,
      `     * ${name}_hal_delay_ms(). */`,
    ];
  }
  return [
    "    /* TODO(driverge): implement the power-on / reset init sequence — the",
    "     * correct register write order and values, plus any required startup",
    `     * delay. See fill_in_brief.init_sequence_todo. Use ${writeRegisterCall}`,
    `     * and ${name}_hal_delay_ms(). */`,
  ];
}

export function makeFiles(
  name: string,
  header: string[],
  source: string[],
  ext: { header: string; source: string } = { header: "h", source: "c" },
): GeneratedFile[] {
  return [
    { path: `${name}.${ext.header}`, content: `${header.join("\n").replace(/\n{3,}/g, "\n\n")}` },
    { path: `${name}.${ext.source}`, content: `${source.join("\n").replace(/\n{3,}/g, "\n\n")}` },
  ];
}

/**
 * Render the portable thin-HAL driver skeleton for a validated datasheet.
 * DeviceInterface is a 2-member discriminated union, so narrowing on `kind`
 * here — rather than casting inside registerDriver/commandDriver — lets both
 * take an explicit, correctly-typed array with no cast. Any kind other than
 * "command_set" is treated as register_map, matching buildInterface's
 * register-first fallback (see schema/assemble) exactly.
 */
export function generatePortableDriver(json: DatasheetJson): DriverArtifact {
  const part = json.metadata.part;
  const name = slug(part);
  const prefix = macro(name);
  return json.interface.kind === "command_set"
    ? commandDriver(json, json.interface.commands, name, prefix)
    : registerDriver(json, json.interface.registers, name, prefix);
}
