// Portable thin-HAL codegen. Renders a deterministic C driver skeleton from the
// frozen DatasheetJson: register/command constants, bit-field mask+shift macros,
// the per-bus thin-HAL seam (I2C: hal_i2c_read/write + hal_delay_ms; SPI: one
// combined hal_spi_transfer + hal_delay_ms — see BUS_SEAM below and
// thin-hal-non-negotiable) and NOTHING platform-specific, function stubs, and
// TODO(driverge) markers at every spot needing host-AI reasoning. Output is
// reproducible: no timestamps, stable ordering. The host AI fills the brief and
// re-validates via validate_driver.

import { registerWidth, type Register } from "../pdf/types.js";
import type { Command, DatasheetJson } from "../schema/types.js";
import { HEX_ONLY, fieldMask, macro, maskHex, slug } from "./ident.js";
import type { DriverArtifact, FillInBrief, GeneratedFile } from "./types.js";

const AUTOGEN = (part: string, mfr: string, busLine: string): string =>
  [
    "/*",
    ` * ${part} driver — portable thin-HAL skeleton (generated by Driverge).`,
    ` * Manufacturer: ${mfr}`,
    ` * ${busLine}`,
    " *",
    " * This is a deterministic skeleton. Every TODO(driverge) marks a spot the",
    " * host AI must complete (init sequence, vendor quirks, docs) using the",
    " * datasheet JSON, then confirm with the validate_driver tool.",
    " *",
    " * Portability rule: this driver calls ONLY the hal_* seam below — never a",
    " * vendor peripheral API. Implement the seam once per platform.",
    " */",
  ].join("\n");

// ---------------------------------------------------------------------------
// register_map
// ---------------------------------------------------------------------------

function registerConstants(prefix: string, registers: Register[]): string[] {
  const lines: string[] = ["/* Register addresses. */"];
  const seen = new Set<string>();
  for (const r of registers) {
    if (!HEX_ONLY.test(r.address)) continue; // skip ranges like "0xE1…0xF0"
    const macroName = `${prefix}_REG_${macro(r.name)}`;
    if (seen.has(macroName)) continue;
    seen.add(macroName);
    lines.push(`#define ${macroName} ${r.address.toUpperCase().replace("0X", "0x")}`);
  }
  return lines;
}

/** Where the host AI must enumerate a register map that Driverge couldn't extract. */
function registerMapTodo(prefix: string, pages: number[]): string[] {
  const where = pages.length
    ? ` (register section detected on page(s) ${pages.join(", ")})`
    : "";
  return [
    "/* Register map. */",
    "/* TODO(driverge): Driverge could not auto-extract this device's register map",
    ` * from the datasheet${where}. Enumerate the registers from the datasheet (read`,
    " * the driverge://datasheet resource) and add one line per register:",
    ` *     #define ${prefix}_REG_<NAME> 0x..`,
    ` * plus ${prefix}_<REG>_<FIELD>_MASK / _SHIFT macros for any bit fields. */`,
  ];
}

/** Where the host AI must enumerate a command set that Driverge couldn't extract. */
function commandSetTodo(prefix: string, pages: number[]): string[] {
  const where = pages.length
    ? ` (command section detected on page(s) ${pages.join(", ")})`
    : "";
  return [
    "/* Command codes. */",
    "/* TODO(driverge): Driverge could not auto-extract this device's command set",
    ` * from the datasheet${where}. Enumerate the commands from the datasheet (read`,
    " * the driverge://datasheet resource) and add one line per command:",
    ` *     #define ${prefix}_CMD_<NAME> 0x.. */`,
  ];
}

// ---------------------------------------------------------------------------
// bus -> thin-HAL seam registry
// ---------------------------------------------------------------------------
//
// Each supported register_map bus contributes: the seam declaration line(s)
// (rendered in the header, right below the "Thin-HAL seam" comment), the
// driver-handle struct field, and the read_register/write_register bodies.
// hal_delay_ms is common to every bus and stays outside this table. Session C
// adds a CAN row here — keep each row self-contained so a new bus never
// touches the others.
//
// UART is the odd row out: unlike I2C/SPI, UART has NO universal
// register-access primitive — there's no address/register concept on the
// wire, just a byte pipe, so read_register/write_register have no honest
// implementation here. Its readBody/writeBody are therefore unused (see
// uartFramingBody below, which renders a TODO(driverge) framing gap directly
// in registerDriver/commandDriver instead of a seam call) — kept as empty
// arrays purely so BusSeam's shape stays uniform across buses.

type RegisterMapBus = "I2C" | "SPI" | "UART";

interface BusSeam {
  /** Lines appended after the "Thin-HAL seam" header comment, in order. */
  decl: string[];
  /** Field(s) for the driver handle typedef struct. */
  handleField: string;
  /** Body of <name>_read_register (dev, reg, value already in scope). Unused for UART. */
  readBody: string[];
  /** Body of <name>_write_register (dev, reg, value already in scope). Unused for UART. */
  writeBody: string[];
}

const BUS_SEAM: Record<RegisterMapBus, BusSeam> = {
  I2C: {
    decl: [
      "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
      "void hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
    ],
    handleField: "    uint8_t i2c_addr;",
    readBody: ["    hal_i2c_read(dev->i2c_addr, reg, value, 1);"],
    writeBody: ["    hal_i2c_write(dev->i2c_addr, reg, &value, 1);"],
  },
  SPI: {
    decl: [
      "/* One call = one CS-framed transaction: CS is asserted, tx_len bytes are",
      " * clocked out, then rx_len bytes are clocked in, then CS is deasserted.",
      " * tx/rx may be NULL when their respective length is 0. CS is handled",
      " * entirely inside hal_spi_transfer — callers never touch it. */",
      "void hal_spi_transfer(const uint8_t *tx, uint16_t tx_len, uint8_t *rx, uint16_t rx_len);",
    ],
    handleField: "    uint8_t _reserved; /* platform CS handled in hal_spi_transfer */",
    readBody: ["    hal_spi_transfer(&reg, 1, value, 1);"],
    writeBody: [
      "    uint8_t frame[2];",
      "    frame[0] = reg;",
      "    frame[1] = value;",
      "    hal_spi_transfer(frame, 2, NULL, 0);",
    ],
  },
  UART: {
    decl: [
      "/* hal_uart_write is a blocking write of len bytes. */",
      "/* hal_uart_read reads up to len bytes and returns the count actually read",
      " * within timeout_ms. */",
      "void hal_uart_write(const uint8_t *data, uint16_t len);",
      "uint16_t hal_uart_read(uint8_t *data, uint16_t len, uint32_t timeout_ms);",
    ],
    handleField:
      "    uint8_t _reserved; /* platform UART handle is bound inside the hal_uart_* implementation */",
    readBody: [],
    writeBody: [],
  },
};

/** Which BUS_SEAM row a protocol.bus resolves to. "unknown" defaults to the I2C
 *  seam, matching the pre-existing (pre-Session-B) fallback behavior. */
function seamBusFor(bus: string): RegisterMapBus {
  if (bus === "SPI") return "SPI";
  if (bus === "UART") return "UART";
  return "I2C";
}

// UART has no universal register/command framing (start bytes, IDs, checksums
// are all device-specific — see decisions: thin-hal-non-negotiable), so rather
// than fabricate a wire format, the generated body is a deliberate
// TODO(driverge) reasoning gap over the raw hal_uart_write/hal_uart_read seam:
// a compilable placeholder (params voided, returns -1) that names both seam
// functions so the host AI knows exactly what to build on top of. See
// fill_in_brief.framing_todo.
function uartFramingBody(params: string[]): string[] {
  return [
    "    /* TODO(driverge): this device has no universal UART register/command",
    "     * framing — build the request frame and call hal_uart_write(), then",
    "     * parse the response via hal_uart_read(). See fill_in_brief.framing_todo. */",
    ...params.map((p) => `    (void)${p};`),
    "    return -1;",
  ];
}

function bitFieldMacros(prefix: string, registers: Register[]): string[] {
  const lines: string[] = [];
  for (const r of registers) {
    if (r.bitFields.length === 0) continue;
    const width = registerWidth(r);
    const widthNote = width > 8 ? ` (${width}-bit register)` : "";
    lines.push("", `/* ${r.name} bit fields${widthNote}. */`);
    for (const f of r.bitFields) {
      const base = `${prefix}_${macro(r.name)}_${macro(f.name)}`;
      lines.push(`#define ${base}_MASK  ${maskHex(fieldMask(f.msb, f.lsb, width), width)}`);
      lines.push(`#define ${base}_SHIFT ${f.lsb}`);
    }
  }
  return lines;
}

function registerDriver(
  json: DatasheetJson,
  registers: Register[],
  name: string,
  prefix: string,
): DriverArtifact {
  const busKind = seamBusFor(json.protocol.bus);
  const spi = busKind === "SPI";
  const uart = busKind === "UART";
  const seam = BUS_SEAM[busKind];
  const addr = json.protocol.addresses?.[0];
  const guard = `${prefix}_H`;
  const type = `${name}_t`;

  const header: string[] = [
    AUTOGEN(
      json.metadata.part || name,
      json.metadata.manufacturer,
      spi
        ? "Bus: SPI"
        : uart
          ? "Bus: UART"
          : `Bus: I2C, address ${addr ?? "(unknown — see TODO)"}`,
    ),
    "",
    `#ifndef ${guard}`,
    `#define ${guard}`,
    "",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    '#ifdef __cplusplus',
    'extern "C" {',
    "#endif",
    "",
  ];

  if (!spi && !uart) {
    if (addr) {
      header.push("/* I2C device address. */", `#define ${prefix}_I2C_ADDR ${addr}`, "");
    } else {
      header.push(
        "/* TODO(driverge): set the I2C device address (not found in the datasheet parse). */",
        `#define ${prefix}_I2C_ADDR 0x00`,
        "",
      );
    }
  }

  const regLines = registerConstants(prefix, registers);
  const hasRegs = regLines.some((l) => l.startsWith("#define"));
  header.push(
    ...(hasRegs
      ? regLines
      : registerMapTodo(prefix, json.extraction?.detectedPages ?? [])),
  );
  if (registers.some((r) => registerWidth(r) > 8)) {
    header.push(
      "",
      "/* NOTE: some registers here are wider than 8 bits (see the per-register",
      " * annotations). Bit-field masks are register-width correct; multi-byte access",
      " * framing (byte order / transfer size) is device-specific and belongs on the",
      " * hal_* seam. */",
    );
  }
  const bits = bitFieldMacros(prefix, registers);
  if (bits.length > 0) header.push("", "/* Bit-field mask/shift accessors. */", ...bits);

  header.push(
    "",
    "/* Thin-HAL seam — implement these for your platform (see thin-hal). */",
    ...seam.decl,
    "void hal_delay_ms (uint32_t ms);",
    "",
    "/* Driver handle. */",
    `typedef struct {`,
    seam.handleField,
    `} ${type};`,
    "",
    "/* Public API. */",
    `int ${name}_init(${type} *dev);`,
    `int ${name}_read_register(${type} *dev, uint8_t reg, uint8_t *value);`,
    `int ${name}_write_register(${type} *dev, uint8_t reg, uint8_t value);`,
    "",
    '#ifdef __cplusplus',
    "}",
    "#endif",
    `#endif /* ${guard} */`,
    "",
  );

  const readBody = uart
    ? uartFramingBody(["dev", "reg", "value"])
    : ["    if (dev == NULL || value == NULL) {", "        return -1;", "    }", ...seam.readBody, "    return 0;"];
  const writeBody = uart
    ? uartFramingBody(["dev", "reg", "value"])
    : ["    if (dev == NULL) {", "        return -1;", "    }", ...seam.writeBody, "    return 0;"];

  const source: string[] = [
    `#include "${name}.h"`,
    "",
    `int ${name}_init(${type} *dev) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    ...(spi || uart ? [] : [`    dev->i2c_addr = ${prefix}_I2C_ADDR;`]),
    ...(uart
      ? [
          "    /* TODO(driverge): implement the power-on / reset init sequence — the",
          "     * correct command/frame sequence and any required startup delay. See",
          "     * fill_in_brief.init_sequence_todo and fill_in_brief.framing_todo. Use",
          "     * hal_uart_write()/hal_uart_read() and hal_delay_ms(). */",
        ]
      : [
          "    /* TODO(driverge): implement the power-on / reset init sequence — the",
          "     * correct register write order and values, plus any required startup",
          `     * delay. See fill_in_brief.init_sequence_todo. Use ${name}_write_register()`,
          "     * and hal_delay_ms(). */",
        ]),
    "    return 0;",
    "}",
    "",
    `int ${name}_read_register(${type} *dev, uint8_t reg, uint8_t *value) {`,
    ...readBody,
    "}",
    "",
    `int ${name}_write_register(${type} *dev, uint8_t reg, uint8_t value) {`,
    ...writeBody,
    "}",
    "",
  ];

  const brief = registerBrief(json);
  if (!hasRegs) {
    brief.register_map_todo = `Enumerate ${json.metadata.part || name}'s register map from the datasheet — Driverge could not auto-extract it. Add a "#define ${prefix}_REG_<NAME> 0x.." for each register address (and ${prefix}_<REG>_<FIELD>_MASK/_SHIFT for bit fields) using the driverge://datasheet resource, then wire the read/write helpers accordingly.`;
  }
  return {
    files: makeFiles(name, header, source),
    fill_in_brief: brief,
  };
}

function registerBrief(json: DatasheetJson): FillInBrief {
  const part = json.metadata.part || "the device";
  const name = slug(part);
  const quirks = [
    `Capture vendor timing/behavior quirks for ${part} (e.g. mandatory power-on delay, soft-reset requirement, read-back constraints) and enforce them in ${name}_init using hal_delay_ms.`,
  ];
  if (json.protocol.bus === "SPI") {
    quirks.push(
      "Verify the register address bit convention: many SPI chips set the address MSB for reads (e.g. 0x80 | reg) — check the datasheet's SPI framing and adjust read_register/write_register.",
    );
  }
  if (json.protocol.bus === "UART") {
    quirks.push(
      "Verify the response checksum algorithm from the datasheet before trusting frame data — vendor checksum/CRC methods for UART command-and-response parts vary.",
    );
  }
  const brief: FillInBrief = {
    init_sequence_todo: `Determine the correct power-on/reset init sequence for ${part}: which registers to write, in what order, with what values (mode/config), and any required startup delay. Read the datasheet init/operation section via the driverge://datasheet resource.`,
    quirks_todo: quirks.join(" "),
    doc_todo:
      "Add Doxygen comments for all public functions and any device-specific compensation/conversion formulas.",
  };
  if (json.protocol.bus === "UART") {
    brief.framing_todo = `Implement ${name}'s UART frame protocol in read_register/write_register: build request frames with hal_uart_write and parse responses with hal_uart_read, per the datasheet's communication/frame-format section.`;
  }
  return brief;
}

// ---------------------------------------------------------------------------
// command_set
// ---------------------------------------------------------------------------

function commandDriver(
  json: DatasheetJson,
  commands: Command[],
  name: string,
  prefix: string,
): DriverArtifact {
  const uart = json.protocol.bus === "UART";
  const addr = json.protocol.addresses?.[0];
  const crc = commands.find((c) => c.crc)?.crc;
  const guard = `${prefix}_H`;
  const type = `${name}_t`;

  const header: string[] = [
    AUTOGEN(
      json.metadata.part || name,
      json.metadata.manufacturer,
      uart
        ? "Bus: UART · command-set device"
        : `Bus: I2C, address ${addr ?? "(unknown — see TODO)"} · command-set device`,
    ),
    "",
    `#ifndef ${guard}`,
    `#define ${guard}`,
    "",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    '#ifdef __cplusplus',
    'extern "C" {',
    "#endif",
    "",
  ];

  if (uart) {
    // No bus device address on UART — only I2C command-set parts get an
    // *_I2C_ADDR macro (see fill_in_brief.framing_todo for the UART reasoning
    // gap this leaves instead).
  } else if (addr) {
    header.push("/* I2C device address. */", `#define ${prefix}_I2C_ADDR ${addr}`, "");
  } else {
    header.push(
      "/* TODO(driverge): set the I2C device address. */",
      `#define ${prefix}_I2C_ADDR 0x00`,
      "",
    );
  }

  if (commands.length === 0) {
    header.push(...commandSetTodo(prefix, json.extraction?.detectedPages ?? []));
  } else {
    header.push("/* Command codes. */");
    const seen = new Set<string>();
    for (const c of commands) {
      const macroName = `${prefix}_CMD_${macro(c.name)}`;
      if (seen.has(macroName)) continue;
      seen.add(macroName);
      const line = `#define ${macroName} ${c.code.toUpperCase().replace("0X", "0x")}`;
      header.push(
        c.params && c.params.length > 0
          ? `${line}  /* params: ${c.params.join(", ")} */`
          : line,
      );
    }
  }

  if (crc) {
    header.push(
      "",
      `/* CRC-${crc.width} checksum parameters. */`,
      `#define ${prefix}_CRC_POLY ${crc.poly}`,
      `#define ${prefix}_CRC_INIT ${crc.init}`,
    );
  }

  header.push(
    "",
    "/* Thin-HAL seam — implement these for your platform (see thin-hal). */",
    ...(uart
      ? BUS_SEAM.UART.decl
      : [
          "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
          "void hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
        ]),
    "void hal_delay_ms (uint32_t ms);",
    "",
    "/* Driver handle. */",
    "typedef struct {",
    uart ? BUS_SEAM.UART.handleField : "    uint8_t i2c_addr;",
    `} ${type};`,
    "",
    "/* Public API. */",
    `int ${name}_init(${type} *dev);`,
    `int ${name}_send_command(${type} *dev, uint16_t command);`,
    `int ${name}_read_data(${type} *dev, uint8_t *buffer, uint16_t len);`,
    ...(crc ? [`uint8_t ${name}_crc8(const uint8_t *data, uint16_t len);`] : []),
    "",
    '#ifdef __cplusplus',
    "}",
    "#endif",
    `#endif /* ${guard} */`,
    "",
  );

  const source: string[] = [
    `#include "${name}.h"`,
    "",
    `int ${name}_init(${type} *dev) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    ...(uart ? [] : [`    dev->i2c_addr = ${prefix}_I2C_ADDR;`]),
    "    /* TODO(driverge): power-up / soft-reset sequence and startup delay. See",
    "     * fill_in_brief.init_sequence_todo. */",
    "    return 0;",
    "}",
    "",
    `int ${name}_send_command(${type} *dev, uint16_t command) {`,
    ...(uart
      ? uartFramingBody(["dev", "command"])
      : [
          "    uint8_t msb;",
          "    uint8_t lsb;",
          "    if (dev == NULL) {",
          "        return -1;",
          "    }",
          "    msb = (uint8_t)(command >> 8);",
          "    lsb = (uint8_t)(command & 0xFF);",
          "    /* Command frame = [MSB][LSB]. hal_i2c_write emits the reg byte then the",
          "     * data bytes, so MSB-as-reg + LSB-as-data yields the correct 2-byte frame. */",
          "    hal_i2c_write(dev->i2c_addr, msb, &lsb, 1);",
          "    return 0;",
        ]),
    "}",
    "",
    `int ${name}_read_data(${type} *dev, uint8_t *buffer, uint16_t len) {`,
    ...(uart
      ? uartFramingBody(["dev", "buffer", "len"])
      : [
          "    if (dev == NULL || buffer == NULL) {",
          "        return -1;",
          "    }",
          "    /* TODO(driverge): read `len` response bytes (data words each followed by a",
          "     * CRC byte). Most command-set parts use a plain I2C read with no pointer",
          "     * byte — adapt the HAL call to your platform, then check each word with",
          `     * ${name}_crc8(). See fill_in_brief.quirks_todo. */`,
          "    (void)dev;",
          "    (void)buffer;",
          "    (void)len;",
          "    return 0;",
        ]),
    "}",
    "",
  ];

  if (crc) {
    source.push(
      `uint8_t ${name}_crc8(const uint8_t *data, uint16_t len) {`,
      "    (void)data;",
      "    (void)len;",
      `    /* TODO(driverge): implement CRC-${crc.width} (poly ${prefix}_CRC_POLY, init`,
      `     * ${prefix}_CRC_INIT) per the datasheet checksum section. See`,
      "     * fill_in_brief.crc_todo. */",
      "    return 0;",
      "}",
      "",
    );
  }

  const brief: FillInBrief = {
    init_sequence_todo: `Determine the power-up / soft-reset sequence and any startup delay for ${json.metadata.part || "the device"}.`,
    quirks_todo: uart
      ? `Verify the response checksum algorithm from the datasheet before trusting ${name}_read_data's output — vendor checksum/CRC methods vary by part.`
      : `Implement ${name}_read_data for this part's actual read framing (clock stretching vs. fixed delay, number of data+CRC words per command) using the driverge://datasheet resource.`,
    doc_todo: "Add Doxygen comments for all public functions and document each command's response layout.",
  };
  if (crc) {
    brief.crc_todo = `Implement ${name}_crc8: CRC-${crc.width}, polynomial ${crc.poly}, init ${crc.init}, per the datasheet checksum section.`;
  }
  if (commands.length === 0) {
    brief.command_set_todo = `Enumerate ${json.metadata.part || name}'s command set from the datasheet — Driverge could not auto-extract it. Add a "#define ${prefix}_CMD_<NAME> 0x.." for each command using the driverge://datasheet resource.`;
  }
  if (uart) {
    brief.framing_todo = `Implement ${name}'s UART frame protocol in send_command/read_data: build request frames with hal_uart_write and parse responses with hal_uart_read, per the datasheet's communication/frame-format section.`;
  }

  return { files: makeFiles(name, header, source), fill_in_brief: brief };
}

// ---------------------------------------------------------------------------

function makeFiles(name: string, header: string[], source: string[]): GeneratedFile[] {
  return [
    { path: `${name}.h`, content: `${header.join("\n").replace(/\n{3,}/g, "\n\n")}` },
    { path: `${name}.c`, content: `${source.join("\n").replace(/\n{3,}/g, "\n\n")}` },
  ];
}

/**
 * Render the portable thin-HAL driver skeleton for a validated datasheet.
 * DeviceInterface is a 2-member discriminated union, so narrowing on `kind`
 * here — rather than casting inside registerDriver/commandDriver — lets both
 * take an explicit, correctly-typed array with no cast. Any kind other than
 * "command_set" is treated as register_map, matching buildInterface's
 * register-first fallback (see schema/assemble) exactly.
 */
export function generatePortableDriver(json: DatasheetJson): DriverArtifact {
  const part = json.metadata.part;
  const name = slug(part);
  const prefix = macro(name);
  return json.interface.kind === "command_set"
    ? commandDriver(json, json.interface.commands, name, prefix)
    : registerDriver(json, json.interface.registers, name, prefix);
}
