// Portable thin-HAL codegen. Renders a deterministic C driver skeleton from the
// frozen DatasheetJson: register/command constants, bit-field mask+shift macros,
// the 5-function thin-HAL seam (and NOTHING platform-specific — see
// thin-hal-non-negotiable), function stubs, and TODO(driverge) markers at every
// spot needing host-AI reasoning. Output is reproducible: no timestamps, stable
// ordering. The host AI fills the brief and re-validates via validate_driver.

import type { Register } from "../pdf/types.js";
import type { Command, DatasheetJson } from "../schema/types.js";
import { HEX_ONLY, fieldMask, hex2, macro, slug } from "./ident.js";
import type { DriverArtifact, FillInBrief, GeneratedFile } from "./types.js";

const AUTOGEN = (part: string, mfr: string, busLine: string): string =>
  [
    "/*",
    ` * ${part} driver — portable thin-HAL skeleton (generated by Driverge).`,
    ` * Manufacturer: ${mfr}`,
    ` * ${busLine}`,
    " *",
    " * This is a deterministic skeleton. Every TODO(driverge) marks a spot the",
    " * host AI must complete (init sequence, vendor quirks, docs) using the",
    " * datasheet JSON, then confirm with the validate_driver tool.",
    " *",
    " * Portability rule: this driver calls ONLY the hal_* seam below — never a",
    " * vendor peripheral API. Implement the seam once per platform.",
    " */",
  ].join("\n");

// ---------------------------------------------------------------------------
// register_map
// ---------------------------------------------------------------------------

function registerConstants(prefix: string, registers: Register[]): string[] {
  const lines: string[] = ["/* Register addresses. */"];
  const seen = new Set<string>();
  for (const r of registers) {
    if (!HEX_ONLY.test(r.address)) continue; // skip ranges like "0xE1…0xF0"
    const macroName = `${prefix}_REG_${macro(r.name)}`;
    if (seen.has(macroName)) continue;
    seen.add(macroName);
    lines.push(`#define ${macroName} ${r.address.toUpperCase().replace("0X", "0x")}`);
  }
  return lines;
}

function bitFieldMacros(prefix: string, registers: Register[]): string[] {
  const lines: string[] = [];
  for (const r of registers) {
    if (r.bitFields.length === 0) continue;
    lines.push("", `/* ${r.name} bit fields. */`);
    for (const f of r.bitFields) {
      const base = `${prefix}_${macro(r.name)}_${macro(f.name)}`;
      lines.push(`#define ${base}_MASK  ${hex2(fieldMask(f.msb, f.lsb))}`);
      lines.push(`#define ${base}_SHIFT ${f.lsb}`);
    }
  }
  return lines;
}

function registerDriver(
  json: DatasheetJson,
  name: string,
  prefix: string,
): DriverArtifact {
  const registers = (json.interface as { registers: Register[] }).registers;
  const spi = json.protocol.bus === "SPI";
  const addr = json.protocol.addresses?.[0];
  const guard = `${prefix}_H`;
  const type = `${name}_t`;

  const header: string[] = [
    AUTOGEN(
      json.metadata.part || name,
      json.metadata.manufacturer,
      spi ? "Bus: SPI" : `Bus: I2C, address ${addr ?? "(unknown — see TODO)"}`,
    ),
    "",
    `#ifndef ${guard}`,
    `#define ${guard}`,
    "",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    '#ifdef __cplusplus',
    'extern "C" {',
    "#endif",
    "",
  ];

  if (!spi) {
    if (addr) {
      header.push("/* I2C device address. */", `#define ${prefix}_I2C_ADDR ${addr}`, "");
    } else {
      header.push(
        "/* TODO(driverge): set the I2C device address (not found in the datasheet parse). */",
        `#define ${prefix}_I2C_ADDR 0x00`,
        "",
      );
    }
  }

  header.push(...registerConstants(prefix, registers));
  const bits = bitFieldMacros(prefix, registers);
  if (bits.length > 0) header.push("", "/* Bit-field mask/shift accessors. */", ...bits);

  header.push(
    "",
    "/* Thin-HAL seam — implement these for your platform (see thin-hal). */",
    ...(spi
      ? [
          "void hal_spi_write(uint8_t *data, uint16_t len);",
          "void hal_spi_read (uint8_t *data, uint16_t len);",
        ]
      : [
          "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
          "void hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
        ]),
    "void hal_delay_ms (uint32_t ms);",
    "",
    "/* Driver handle. */",
    `typedef struct {`,
    spi ? "    uint8_t _reserved; /* platform CS handled in hal_spi_* */" : "    uint8_t i2c_addr;",
    `} ${type};`,
    "",
    "/* Public API. */",
    `int ${name}_init(${type} *dev);`,
    `int ${name}_read_register(${type} *dev, uint8_t reg, uint8_t *value);`,
    `int ${name}_write_register(${type} *dev, uint8_t reg, uint8_t value);`,
    "",
    '#ifdef __cplusplus',
    "}",
    "#endif",
    `#endif /* ${guard} */`,
    "",
  );

  const readBody = spi
    ? ["    hal_spi_write(&reg, 1);", "    hal_spi_read(value, 1);"]
    : ["    hal_i2c_read(dev->i2c_addr, reg, value, 1);"];
  const writeBody = spi
    ? ["    uint8_t frame[2];", "    frame[0] = reg;", "    frame[1] = value;", "    hal_spi_write(frame, 2);"]
    : ["    hal_i2c_write(dev->i2c_addr, reg, &value, 1);"];

  const source: string[] = [
    `#include "${name}.h"`,
    "",
    `int ${name}_init(${type} *dev) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    ...(spi ? [] : [`    dev->i2c_addr = ${prefix}_I2C_ADDR;`]),
    "    /* TODO(driverge): implement the power-on / reset init sequence — the",
    "     * correct register write order and values, plus any required startup",
    `     * delay. See fill_in_brief.init_sequence_todo. Use ${name}_write_register()`,
    "     * and hal_delay_ms(). */",
    "    return 0;",
    "}",
    "",
    `int ${name}_read_register(${type} *dev, uint8_t reg, uint8_t *value) {`,
    "    if (dev == NULL || value == NULL) {",
    "        return -1;",
    "    }",
    ...readBody,
    "    return 0;",
    "}",
    "",
    `int ${name}_write_register(${type} *dev, uint8_t reg, uint8_t value) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    ...writeBody,
    "    return 0;",
    "}",
    "",
  ];

  return {
    files: makeFiles(name, header, source),
    fill_in_brief: registerBrief(json),
  };
}

function registerBrief(json: DatasheetJson): FillInBrief {
  const part = json.metadata.part || "the device";
  return {
    init_sequence_todo: `Determine the correct power-on/reset init sequence for ${part}: which registers to write, in what order, with what values (mode/config), and any required startup delay. Read the datasheet init/operation section via the driverge://datasheet resource.`,
    quirks_todo: `Capture vendor timing/behavior quirks for ${part} (e.g. mandatory power-on delay, soft-reset requirement, read-back constraints) and enforce them in ${slug(part)}_init using hal_delay_ms.`,
    doc_todo:
      "Add Doxygen comments for all public functions and any device-specific compensation/conversion formulas.",
  };
}

// ---------------------------------------------------------------------------
// command_set
// ---------------------------------------------------------------------------

function commandDriver(
  json: DatasheetJson,
  name: string,
  prefix: string,
): DriverArtifact {
  const commands = (json.interface as { commands: Command[] }).commands;
  const addr = json.protocol.addresses?.[0];
  const crc = commands.find((c) => c.crc)?.crc;
  const guard = `${prefix}_H`;
  const type = `${name}_t`;

  const header: string[] = [
    AUTOGEN(
      json.metadata.part || name,
      json.metadata.manufacturer,
      `Bus: I2C, address ${addr ?? "(unknown — see TODO)"} · command-set device`,
    ),
    "",
    `#ifndef ${guard}`,
    `#define ${guard}`,
    "",
    "#include <stddef.h>",
    "#include <stdint.h>",
    "",
    '#ifdef __cplusplus',
    'extern "C" {',
    "#endif",
    "",
  ];

  if (addr) {
    header.push("/* I2C device address. */", `#define ${prefix}_I2C_ADDR ${addr}`, "");
  } else {
    header.push(
      "/* TODO(driverge): set the I2C device address. */",
      `#define ${prefix}_I2C_ADDR 0x00`,
      "",
    );
  }

  header.push("/* Command codes. */");
  const seen = new Set<string>();
  for (const c of commands) {
    const macroName = `${prefix}_CMD_${macro(c.name)}`;
    if (seen.has(macroName)) continue;
    seen.add(macroName);
    header.push(`#define ${macroName} ${c.code.toUpperCase().replace("0X", "0x")}`);
  }

  if (crc) {
    header.push(
      "",
      `/* CRC-${crc.width} checksum parameters. */`,
      `#define ${prefix}_CRC_POLY ${crc.poly}`,
      `#define ${prefix}_CRC_INIT ${crc.init}`,
    );
  }

  header.push(
    "",
    "/* Thin-HAL seam — implement these for your platform (see thin-hal). */",
    "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
    "void hal_i2c_read (uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);",
    "void hal_delay_ms (uint32_t ms);",
    "",
    "/* Driver handle. */",
    "typedef struct {",
    "    uint8_t i2c_addr;",
    `} ${type};`,
    "",
    "/* Public API. */",
    `int ${name}_init(${type} *dev);`,
    `int ${name}_send_command(${type} *dev, uint16_t command);`,
    `int ${name}_read_data(${type} *dev, uint8_t *buffer, uint16_t len);`,
    ...(crc ? [`uint8_t ${name}_crc8(const uint8_t *data, uint16_t len);`] : []),
    "",
    '#ifdef __cplusplus',
    "}",
    "#endif",
    `#endif /* ${guard} */`,
    "",
  );

  const source: string[] = [
    `#include "${name}.h"`,
    "",
    `int ${name}_init(${type} *dev) {`,
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    `    dev->i2c_addr = ${prefix}_I2C_ADDR;`,
    "    /* TODO(driverge): power-up / soft-reset sequence and startup delay. See",
    "     * fill_in_brief.init_sequence_todo. */",
    "    return 0;",
    "}",
    "",
    `int ${name}_send_command(${type} *dev, uint16_t command) {`,
    "    uint8_t msb;",
    "    uint8_t lsb;",
    "    if (dev == NULL) {",
    "        return -1;",
    "    }",
    "    msb = (uint8_t)(command >> 8);",
    "    lsb = (uint8_t)(command & 0xFF);",
    "    /* Command frame = [MSB][LSB]. hal_i2c_write emits the reg byte then the",
    "     * data bytes, so MSB-as-reg + LSB-as-data yields the correct 2-byte frame. */",
    "    hal_i2c_write(dev->i2c_addr, msb, &lsb, 1);",
    "    return 0;",
    "}",
    "",
    `int ${name}_read_data(${type} *dev, uint8_t *buffer, uint16_t len) {`,
    "    if (dev == NULL || buffer == NULL) {",
    "        return -1;",
    "    }",
    "    /* TODO(driverge): read `len` response bytes (data words each followed by a",
    "     * CRC byte). Most command-set parts use a plain I2C read with no pointer",
    "     * byte — adapt the HAL call to your platform, then check each word with",
    `     * ${name}_crc8(). See fill_in_brief.quirks_todo. */`,
    "    (void)dev;",
    "    (void)buffer;",
    "    (void)len;",
    "    return 0;",
    "}",
    "",
  ];

  if (crc) {
    source.push(
      `uint8_t ${name}_crc8(const uint8_t *data, uint16_t len) {`,
      "    (void)data;",
      "    (void)len;",
      `    /* TODO(driverge): implement CRC-${crc.width} (poly ${prefix}_CRC_POLY, init`,
      `     * ${prefix}_CRC_INIT) per the datasheet checksum section. See`,
      "     * fill_in_brief.crc_todo. */",
      "    return 0;",
      "}",
      "",
    );
  }

  const brief: FillInBrief = {
    init_sequence_todo: `Determine the power-up / soft-reset sequence and any startup delay for ${json.metadata.part || "the device"}.`,
    quirks_todo: `Implement ${name}_read_data for this part's actual read framing (clock stretching vs. fixed delay, number of data+CRC words per command) using the driverge://datasheet resource.`,
    doc_todo: "Add Doxygen comments for all public functions and document each command's response layout.",
  };
  if (crc) {
    brief.crc_todo = `Implement ${name}_crc8: CRC-${crc.width}, polynomial ${crc.poly}, init ${crc.init}, per the datasheet checksum section.`;
  }

  return { files: makeFiles(name, header, source), fill_in_brief: brief };
}

// ---------------------------------------------------------------------------

function makeFiles(name: string, header: string[], source: string[]): GeneratedFile[] {
  return [
    { path: `${name}.h`, content: `${header.join("\n").replace(/\n{3,}/g, "\n\n")}` },
    { path: `${name}.c`, content: `${source.join("\n").replace(/\n{3,}/g, "\n\n")}` },
  ];
}

/** Render the portable thin-HAL driver skeleton for a validated datasheet. */
export function generatePortableDriver(json: DatasheetJson): DriverArtifact {
  const part = json.metadata.part;
  const name = slug(part);
  const prefix = macro(name);
  return json.interface.kind === "command_set"
    ? commandDriver(json, name, prefix)
    : registerDriver(json, name, prefix);
}
