// STM32 (CubeHAL) target. Like ESP32, a native target pre-fills the thin-HAL
// seam rather than replacing it: the driver is the unchanged portable core plus a
// <part>_hal_stm32.c that implements the bus's thin-HAL seam + hal_delay_ms with
// STM32 CubeHAL (HAL_I2C_Mem_Read/Write, HAL_SPI_Transmit/Receive + a CS GPIO, or
// HAL_UART_Transmit/Receive, plus HAL_Delay). The user binds their peripheral
// handle(s) once via <part>_stm32_bind(); the board/clock bring-up stays in
// their CubeMX project.
//
// I2C/SPI/UART only: the I2C seam hard-codes CubeHAL's HAL_I2C_Mem_* calls and
// references `${PREFIX}_I2C_ADDR`; the SPI seam needs the portable core's
// hal_spi_transfer declaration; the UART seam (Session B) wraps
// HAL_UART_Transmit/Receive around hal_uart_write/hal_uart_read. Any other bus
// (unknown) has no CubeHAL seam here, so this target refuses
// (UnsupportedBusError) rather than emit an uncompilable seam.

import type { DatasheetJson } from "../schema/types.js";
import { prefixOf, slug } from "./ident.js";
import { generatePortableCppDriver } from "./portable-cpp.js";
import { generatePortableDriver } from "./portable.js";
import { UnsupportedBusError } from "./types.js";
import type { CodegenLanguage, DriverArtifact, GeneratedFile } from "./types.js";

function halImplI2c(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — STM32 CubeHAL seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with STM32",
    " * CubeHAL. \"main.h\" is the CubeMX convention that pulls in your family's HAL",
    " * and I2C_HandleTypeDef — if you don't use CubeMX, include your family header",
    ` * (e.g. stm32f4xx_hal.h) instead. Call ${name}_stm32_bind(&hi2cX) once at`,
    " * startup so the seam knows which I2C peripheral to use.",
    " */",
    `#include "${name}.h"`,
    '#include "main.h"',
    "",
    `#ifndef ${prefix}_I2C_TIMEOUT_MS`,
    `#define ${prefix}_I2C_TIMEOUT_MS 1000`,
    "#endif",
    "",
    `static I2C_HandleTypeDef *s_${name}_hi2c;`,
    "",
    "/* Point the seam at the CubeMX-generated I2C handle (e.g. &hi2c1). */",
    `void ${name}_stm32_bind(I2C_HandleTypeDef *hi2c) {`,
    `    s_${name}_hi2c = hi2c;`,
    "}",
    "",
    "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    "    /* CubeHAL takes the 8-bit (left-shifted) device address. */",
    `    HAL_I2C_Mem_Write(s_${name}_hi2c, (uint16_t)(addr << 1), reg,`,
    `                      I2C_MEMADD_SIZE_8BIT, data, len, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_i2c_read(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    `    HAL_I2C_Mem_Read(s_${name}_hi2c, (uint16_t)(addr << 1), reg,`,
    `                     I2C_MEMADD_SIZE_8BIT, data, len, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    HAL_Delay(ms);",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_stm32.c`, content };
}

function halImplSpi(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — STM32 CubeHAL SPI seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with STM32",
    " * CubeHAL SPI + a GPIO chip-select. \"main.h\" is the CubeMX convention that",
    " * pulls in your family's HAL, SPI_HandleTypeDef and GPIO_TypeDef — if you",
    ` * don't use CubeMX, include your family header (e.g. stm32f4xx_hal.h)`,
    ` * instead. Call ${name}_stm32_bind(&hspiX, CS_GPIO_Port, CS_Pin) once at`,
    " * startup so the seam knows which SPI peripheral and CS pin to use.",
    " */",
    `#include "${name}.h"`,
    '#include "main.h"',
    "",
    `#ifndef ${prefix}_SPI_TIMEOUT_MS`,
    `#define ${prefix}_SPI_TIMEOUT_MS 1000`,
    "#endif",
    "",
    `static SPI_HandleTypeDef *s_${name}_hspi;`,
    `static GPIO_TypeDef *s_${name}_cs_port;`,
    `static uint16_t s_${name}_cs_pin;`,
    "",
    "/* Point the seam at the CubeMX-generated SPI handle (e.g. &hspi1) and the CS",
    " * GPIO pin (e.g. CS_GPIO_Port, CS_Pin). */",
    `void ${name}_stm32_bind(SPI_HandleTypeDef *hspi, GPIO_TypeDef *cs_port, uint16_t cs_pin) {`,
    `    s_${name}_hspi = hspi;`,
    `    s_${name}_cs_port = cs_port;`,
    `    s_${name}_cs_pin = cs_pin;`,
    "}",
    "",
    "void hal_spi_transfer(const uint8_t *tx, uint16_t tx_len, uint8_t *rx, uint16_t rx_len) {",
    `    HAL_GPIO_WritePin(s_${name}_cs_port, s_${name}_cs_pin, GPIO_PIN_RESET);`,
    "    if (tx_len > 0) {",
    `        HAL_SPI_Transmit(s_${name}_hspi, (uint8_t *)tx, tx_len, ${prefix}_SPI_TIMEOUT_MS);`,
    "    }",
    "    if (rx_len > 0) {",
    `        HAL_SPI_Receive(s_${name}_hspi, rx, rx_len, ${prefix}_SPI_TIMEOUT_MS);`,
    "    }",
    `    HAL_GPIO_WritePin(s_${name}_cs_port, s_${name}_cs_pin, GPIO_PIN_SET);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    HAL_Delay(ms);",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_stm32.c`, content };
}

function halImplUart(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — STM32 CubeHAL UART seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with STM32",
    " * CubeHAL UART. \"main.h\" is the CubeMX convention that pulls in your family's",
    " * HAL and UART_HandleTypeDef — if you don't use CubeMX, include your family",
    ` * header (e.g. stm32f4xx_hal.h) instead. Call ${name}_stm32_bind(&huartX) once`,
    " * at startup so the seam knows which UART peripheral to use.",
    " */",
    `#include "${name}.h"`,
    '#include "main.h"',
    "",
    `#ifndef ${prefix}_UART_TIMEOUT_MS`,
    `#define ${prefix}_UART_TIMEOUT_MS 1000`,
    "#endif",
    "",
    `static UART_HandleTypeDef *s_${name}_huart;`,
    "",
    "/* Point the seam at the CubeMX-generated UART handle (e.g. &huart1). */",
    `void ${name}_stm32_bind(UART_HandleTypeDef *huart) {`,
    `    s_${name}_huart = huart;`,
    "}",
    "",
    "void hal_uart_write(const uint8_t *data, uint16_t len) {",
    `    HAL_UART_Transmit(s_${name}_huart, (uint8_t *)data, len, ${prefix}_UART_TIMEOUT_MS);`,
    "}",
    "",
    "uint16_t hal_uart_read(uint8_t *data, uint16_t len, uint32_t timeout_ms) {",
    "    HAL_StatusTypeDef status;",
    `    status = HAL_UART_Receive(s_${name}_huart, data, len, timeout_ms);`,
    "    if (status == HAL_OK) {",
    "        return len;",
    "    }",
    "    /* Timeout/error: CubeHAL stops short of `len` bytes and leaves the number",
    "     * of bytes it still expected in RxXferCount, so (len - RxXferCount) is",
    "     * the count actually received before the timeout fired. */",
    `    return (uint16_t)(len - s_${name}_huart->RxXferCount);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    HAL_Delay(ms);",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_stm32.c`, content };
}

/**
 * Portable core + a CubeHAL seam implementation for the same part. The seam
 * file is always plain C (CubeHAL calls) regardless of language: with language
 * "cpp" the core's .hpp wraps the same hal_* declarations in
 * `extern "C" { ... }`, so this unchanged seam file still links against the
 * class methods — see portable-cpp.ts's EXTERN_C_NOTE.
 */
export function generateStm32Driver(
  json: DatasheetJson,
  opts: { language?: CodegenLanguage } = {},
): DriverArtifact {
  const bus = json.protocol.bus;
  if (bus !== "I2C" && bus !== "SPI" && bus !== "UART") {
    throw new UnsupportedBusError("stm32", bus);
  }
  const name = slug(json.metadata.part);
  const prefix = prefixOf(json.metadata.part);
  const base = opts.language === "cpp" ? generatePortableCppDriver(json) : generatePortableDriver(json);

  const hal =
    bus === "SPI" ? halImplSpi(name, prefix) : bus === "UART" ? halImplUart(name, prefix) : halImplI2c(name, prefix);
  const hal_setup_todo =
    bus === "SPI"
      ? `Configure the SPI peripheral and a CS GPIO output pin in CubeMX (mode/clock per the datasheet's SPI timing section), then call ${name}_stm32_bind(&hspiX, CS_GPIO_Port, CS_Pin) once at startup. Adjust ${prefix}_SPI_TIMEOUT_MS if needed.`
      : bus === "UART"
        ? `Configure the USART/UART peripheral in CubeMX (pins, baud rate, parity, stop bits per the datasheet's serial interface section), then call ${name}_stm32_bind(&huartX) once at startup. Adjust ${prefix}_UART_TIMEOUT_MS if needed.`
        : `Configure the I2C peripheral in CubeMX (pins, clock, 7-bit addressing), then call ${name}_stm32_bind(&hi2cX) once at startup. Adjust ${prefix}_I2C_TIMEOUT_MS if needed.`;

  return {
    files: [...base.files, hal],
    fill_in_brief: {
      ...base.fill_in_brief,
      hal_setup_todo,
    },
  };
}
