// STM32 (CubeHAL) target. Like ESP32, a native target pre-fills the thin-HAL
// seam rather than replacing it: the driver is the unchanged portable core plus a
// <part>_hal_stm32.c that implements hal_i2c_*/hal_delay_ms with STM32 CubeHAL
// (HAL_I2C_Mem_Read/Write, HAL_Delay). The user binds their I2C handle once via
// <part>_stm32_bind(); the board/clock bring-up stays in their CubeMX project.

import type { DatasheetJson } from "../schema/types.js";
import { prefixOf, slug } from "./ident.js";
import { generatePortableDriver } from "./portable.js";
import type { DriverArtifact, GeneratedFile } from "./types.js";

function halImpl(name: string, prefix: string): GeneratedFile {
  const content = [
    "/*",
    ` * ${prefix} — STM32 CubeHAL seam implementation (generated by Driverge).`,
    " *",
    " * Drop this beside the portable core; it fills the thin-HAL seam with STM32",
    " * CubeHAL. \"main.h\" is the CubeMX convention that pulls in your family's HAL",
    " * and I2C_HandleTypeDef — if you don't use CubeMX, include your family header",
    ` * (e.g. stm32f4xx_hal.h) instead. Call ${name}_stm32_bind(&hi2cX) once at`,
    " * startup so the seam knows which I2C peripheral to use.",
    " */",
    `#include "${name}.h"`,
    '#include "main.h"',
    "",
    `#ifndef ${prefix}_I2C_TIMEOUT_MS`,
    `#define ${prefix}_I2C_TIMEOUT_MS 1000`,
    "#endif",
    "",
    `static I2C_HandleTypeDef *s_${name}_hi2c;`,
    "",
    "/* Point the seam at the CubeMX-generated I2C handle (e.g. &hi2c1). */",
    `void ${name}_stm32_bind(I2C_HandleTypeDef *hi2c) {`,
    `    s_${name}_hi2c = hi2c;`,
    "}",
    "",
    "void hal_i2c_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    "    /* CubeHAL takes the 8-bit (left-shifted) device address. */",
    `    HAL_I2C_Mem_Write(s_${name}_hi2c, (uint16_t)(addr << 1), reg,`,
    `                      I2C_MEMADD_SIZE_8BIT, data, len, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_i2c_read(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len) {",
    `    HAL_I2C_Mem_Read(s_${name}_hi2c, (uint16_t)(addr << 1), reg,`,
    `                     I2C_MEMADD_SIZE_8BIT, data, len, ${prefix}_I2C_TIMEOUT_MS);`,
    "}",
    "",
    "void hal_delay_ms(uint32_t ms) {",
    "    HAL_Delay(ms);",
    "}",
    "",
  ].join("\n");
  return { path: `${name}_hal_stm32.c`, content };
}

/** Portable core + a CubeHAL seam implementation for the same part. */
export function generateStm32Driver(json: DatasheetJson): DriverArtifact {
  const name = slug(json.metadata.part);
  const prefix = prefixOf(json.metadata.part);
  const base = generatePortableDriver(json);

  return {
    files: [...base.files, halImpl(name, prefix)],
    fill_in_brief: {
      ...base.fill_in_brief,
      hal_setup_todo: `Configure the I2C peripheral in CubeMX (pins, clock, 7-bit addressing), then call ${name}_stm32_bind(&hi2cX) once at startup. Adjust ${prefix}_I2C_TIMEOUT_MS if needed.`,
    },
  };
}
